### ISSUE TITLE
popen doesn't report errors related to ls globbing too many arguments.

### ISSUE THREAD

**Issue by mklauber** [GUI/lua-resty-auto-ssl#109]
https://github.com/GUI/lua-resty-auto-ssl/blob/8227d90bfa7e6abee5ecf516721df986ef2ab702/lib/resty/auto-ssl/storage_adapters/file.lua#L76-L80

In the line above, if globbing `*:latest` results in `ls` being sent too many arguments, ls returns an error in stderr, and the variable `out` gets no results.  This is invisibly handled as 0 domains, rather than an error.  Should check stderr or the return code to determine if this occurred.  

Possible fix would include switching to using `find`.

**Comment by GUI** [comment]
@mklauber: Thanks for reporting this! This should be fixed in the v0.12.0 release, since we've switched to using `find`, as you suggested. But give a shout if you're still seeing any issue.

**Comment by mklauber** [comment]
@GUI Thanks for the fix, and for the shout.  We actually migrated to the redis backend as a workaround for this, so I can't confirm the fix, but the code looks right to me.
