### ISSUE TITLE
OCSP stapling error: cannot assign requested address 

### ISSUE THREAD

**Issue by byrnedo** [GUI/lua-resty-auto-ssl#113]
`OCSP responder query failed (http://ocsp.int-x3.letsencrypt.org): cannot assign requested address`

Comes up regularly.
Our openresty is in docker, could this be a config issue?

**Comment by byrnedo** [comment]
This error is preceded by 
`2018/01/09 06:47:58 [crit] 34#34: *387591 connect() to [2a02:26f0:d2::58dd:5959]:80 failed (99: Cannot assign requested address), context: ssl_certificate_by_lua*, client: 10.255.0.2, server: 0.0.0.0:443`

**Comment by brianlund** [comment]
It's not the exact same error as in https://github.com/GUI/lua-resty-auto-ssl/issues/12 but you might try turning ipv6 resolving off for nginx, e.g:
`resolver 8.8.8.8 ipv6=off;`

**Comment by byrnedo** [comment]
Thanks @brianlund, that did the trick I think.

**Comment by Bestme-admin** [comment]
thanks. same problem worked for me as well ( ipv6=off; )
