### ISSUE TITLE
ACME v2 and Wildcard

### ISSUE THREAD

**Issue by Laboltus** [GUI/lua-resty-auto-ssl#126]
Hi. 

Since LE has has strict limits for subdomains (20 per week), it would be nice to get support for the recently appeared LE wildcard certificates https://community.letsencrypt.org/t/acme-v2-production-environment-wildcards/55578. As I can see, dehydrated is in the list of ACME v2 clients. Does it mean I can already use wildcards with auto-ssl ?

**Comment by gjongenelen** [comment]
Duplicate of #97
