### ISSUE TITLE
How to debug ssl_certificate.lua failed to run do_ssl ?

### ISSUE THREAD

**Issue by edeis53** [GUI/lua-resty-auto-ssl#134]
We're getting these occassional errors. What would be causing them and how to debug?

```2018/05/08 02:33:41 [error] 13313#13313: *2869 [lua] ssl_certificate.lua:305: ssl_certificate(): auto-ssl: failed to run do_ssl: init_by_lua:90: attempt to index a nil value, context: ssl_certificate_by_lua*, client: xx.xx.xx.xx, server: 0.0.0.0:443```

Certificates are being issued successfully.

When it says `init_by_lua:90` which init_by_lua is it referring to? is this an issue with our server configuration or is it an issue with lua-resty-auto-ssl?

On most occasions the client is requesting with `"Request Missing an Accept Header"` which modsecurity is returning a 403 to the client. However, doesn't seem to be the case for all requests.

**Comment by edeis53** [comment]
Would a request without a hostname, ip only, throw this error too>?
re https://github.com/GUI/lua-resty-auto-ssl/issues/26

**Comment by brianlund** [comment]
I checkout our logs and don't see any of the same error and we get plenty of requests without hostname.
Perhaps take a look at your allow_domain function, it could be from some of your code there.

**Comment by edeis53** [comment]
Confirmed. Error was due to code in allow_domain function.

The error was misleading as the error line reported did not referrer to offending code.

Closing.
