### ISSUE TITLE
Elevated error rates in logs

### ISSUE THREAD

**Issue by domharrington** [GUI/lua-resty-auto-ssl#135]
Hey!

Thanks again for this project. I've been seeing some errors that keep reoccurring in our logs (the error lines contain the failing cals to dehydrated, i've pasted the output of me manually running those commands below). They mainly take 2 forms:

1. Something to do with a license agreement URL being out of date? Sounds similar to #13?

```
$ env HOOK_SECRET=xxxxxxxxxxxxx HOOK_SERVER_PORT=8999 /usr/local/openresty/luajit/bin/resty-auto-ssl/dehydrated --cron --no-lock --domain xxx.example.com --challenge http-01 --config /etc/resty-auto-ssl/letsencrypt/config --hook /usr/local/openresty/luajit/bin/resty-auto-ssl/letsencrypt_hooks
# INFO: Using main config file /etc/resty-auto-ssl/letsencrypt/config
# !! WARNING !! Extra configuration directory /etc/resty-auto-ssl/letsencrypt/conf.d exists, but no configuration found in it.
+ Generating account key...
+ Registering account key with ACME server...
  + ERROR: An error occurred while sending post-request to https://acme-v01.api.letsencrypt.org/acme/new-reg (Status 400)

Details:
{
  "type": "urn:acme:error:malformed",
  "detail": "Provided agreement URL [https://letsencrypt.org/documents/LE-SA-v1.1.1-August-1-2016.pdf] does not match current agreement URL [https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf]",
  "status": 400
}

rm: cannot remove '/etc/resty-auto-ssl/letsencrypt/domains.txt': No such file or directory


Error registering account key. See message above for more information.
```

2. `--accept-terms` being an unknown parameter?

```
env HOOK_SECRET=xxxxxxxxxxxx HOOK_SERVER_PORT=8999 /usr/local/openresty/luajit/bin/resty-auto-ssl/dehydrated --cron --accept-terms --no-lock --domain xxx.example.com --challenge http-01 --config /etc/resty-auto-ssl/letsencrypt/config --hook /usr/local/openresty/luajit/bin/resty-auto-ssl/letsencrypt_hooks
Unknown parameter detected: --accept-terms
```

Current version:
lua-resty-auto-ssl - 0.12.0

Thanks for your help in advance!

**Comment by GUI** [comment]
Hm, this error does seem like it's related to #13, but the fact that it's complaining about `--accept-terms` not being a valid option is curious. I'm wondering if somehow dehydrated didn't get upgraded. If you run `/usr/local/openresty/luajit/bin/resty-auto-ssl/dehydrated --version`, what do you get? I think it should be reporting `0.5.0` if it's running the version that's bundled with lua-resty-auto-ssl v0.12.0.

**Comment by domharrington** [comment]
Managed to fix it! There were some uncommitted local changes on the server in which this was deployed, which was making the deployment fail silently.

Thank you!
