### ISSUE TITLE
Can't find the letsencrypt logs

### ISSUE THREAD

**Issue by joshnabbott** [GUI/lua-resty-auto-ssl#142]
I'm looking for the location of the letsencrypt or dehydrated logs. When using certbot, logs were stored in `/var/log/letsencrypt/letsencrypt.log` where I was able to see the response from letsencrypt in the case that I'd hit a rate limit, or some error had occurred. I'm not able to find that using lua-resty-auto-ssl. Can you point me in the right direction?

**Comment by luto** [comment]
Errors like rate-limits are logged to the nginx error log, so you should find those entries there. Does that work for you?

**Comment by joshnabbott** [comment]
Yep, that works for me. I hadn't thought to check those logs yet. Thank you for the quick response!
