### ISSUE TITLE
Seeing hundreds of auto-ssl: 'lua_shared_dict auto_ssl' might be too small in nginx error logs

### ISSUE THREAD

**Issue by joshnabbott** [GUI/lua-resty-auto-ssl#145]
I'm seeing hundreds of these errors in my nginx error logs:

auto-ssl: 'lua_shared_dict auto_ssl' might be too small - consider increasing its configured size`

Could this error be causing nginx to crash in production and what's an acceptable number to increase this setting to?

**Comment by luto** [comment]
The `auto_ssl` dict acts as a cache for the actual storage (e.g. file or redis); so if it's too small, the cache will loose entries and thus miss domains. This may affect performance but shouldn't lead to any crashes.
What kind of crashes do you see?

> what's an acceptable number to increase this setting to?

That depends on the number of certificates. The default is just 1MB, so it's safe to double or even quadruple it without any impact.

**Comment by joshnabbott** [comment]
@luto thank you for the response. My logs are also full of `client closed connection while waiting for request`. Not necessarily a crash, but investigating what's going on. I'll bump the dict size and see if that makes the previous error go away.
