### ISSUE TITLE
Question about certificate reissue if expired

### ISSUE THREAD

**Issue by bryanus** [GUI/lua-resty-auto-ssl#148]
I am setting up an EC2 instance running auto-ssl. My plan is to create an Auto-Scaling group of my working server, to launch a replacement server in the case that the current one runs into issues.

My image will be essentially clear of certificates, with only a handful of previously-issues certificates on it. More than likely, if this replacement server comes online, the existing certificates would have expired, and any valid certificates on the [now] defunct server would not exist.

In this scenario, would auto-ssl simply renew the expired certificates and issue new certificates for the missing ones?

Also, what would be faster? Renewing expired certificates or issuing new ones? I could also image the server once it has most of my domains issued, so the image contains stored certificates (albeit expired).

Last question: Is there a way to clear out all of the existing certificates? If I delete the cert for a domain from /etc/resty-auto-ssl/letsencrypt/certs/, restart the server, then watch the logs for that domain, the certificate seems to already exist somewhere and I don't see a new cert for that domain in that location. 

TIA!

**Comment by brianlund** [comment]
Why not use the redis storage adapter (and a separate redis instance / elasticache) and keep the certificates there? Then it doesn't matter what is in the image.

**Comment by luto** [comment]
> Last question: Is there a way to clear out all of the existing certificates? If I delete the cert for a domain from /etc/resty-auto-ssl/letsencrypt/certs/

There is `/etc/rest-auto-ssl/storage`, which is the primary storage for certificates.

**Comment by bryanus** [comment]
> Why not use the redis storage adapter (and a separate redis instance / elasticache) and keep the certificates there? Then it doesn't matter what is in the image.

Hmm, I hadn't thought of that actually. But that's a good idea. I guess I was trying to roll this as inexpensively as possible, but it looks like AWS has 12-months free tier for a t2,micro that would likely more than suffice for my needs. I'll definitely look into this option.

But I'm still curious to know if auto-ssl would renew any expired certificates and/or re-issue new certificates for the missing ones, on a 'clean' instance?

> There is /etc/rest-auto-ssl/storage, which is the primary storage for certificates.

Awesome, thanks! I suppose in an attempt to answer my previous question, I could try deleting the certificate storage, then see what happens when previously issued domains hit the server and see if they get re-issued or run into errors.

**Comment by bryanus** [comment]
ok, I've started up a Redis cluster, and am able to telnet to it from my resty instance, but once I add in the Redis storage_adapter, I'm running into issues with certs. Is my config correctly formatted?

```
init_by_lua_block {
    auto_ssl = (require "resty.auto-ssl").new()
    auto_ssl:set("storage_adapter", "resty.auto-ssl.storage_adapters.redis")
    auto_ssl:set("host", "redis-ssl.xxx2hl4.ng.0001.usw2.cache.amazonaws.com")
    auto_ssl:set("allow_domain", function(domain)
      return true
    end)
    auto_ssl:init()
}
```

Here's the error that's popping up:

```
2018/06/29 17:57:26 [error] 1262#1262: *160 [lua] ssl_certificate.lua:134: get_cert_der(): auto-ssl: error fetching certificate from storage for example.com: connection refused, context: ssl_certificate_by_lua*, client: 11.22.33.444, server: 0.0.0.0:443
2018/06/29 17:57:26 [error] 1262#1262: *154 connect() failed (111: Connection refused), context: ssl_certificate_by_lua*, client: 11.22.33.444, server: 0.0.0.0:443
2018/06/29 17:57:26 [error] 1262#1262: *154 [lua] ssl_certificate.lua:77: issue_cert(): auto-ssl: failed to obtain lock: connection refused, context: ssl_certificate_by_lua*, client: 11.22.33.444, server: 0.0.0.0:443
2018/06/29 17:57:26 [error] 1262#1262: *154 [lua] ssl_certificate.lua:286: auto-ssl: could not get certificate for example.com - using fallback - failed to get or issue certificate, context: ssl_certificate_by_lua*, client:  11.22.33.444, server: 0.0.0.0:443
```

(FWIW, this was for a previously issued domain that I had deleted from /storage and /certs and rebooted. When viewing the access logs, I didn't even see an attempt to validate the challenge either.)

Am I missing some additional options for the redis configuration? Not sure what auth and db should be set to, if required.

**Comment by luto** [comment]
The redis host needs to be set [like this](https://github.com/GUI/lua-resty-auto-ssl#redis):

```lua
auto_ssl:set("redis", {
  host = "10.10.10.1"
})
```

:)

**Comment by bryanus** [comment]
Thanks for your quick reply, Luto!

OK, so now I have it like this:

```
init_by_lua_block {
    auto_ssl = (require "resty.auto-ssl").new()
    auto_ssl:set("storage_adapter", "resty.auto-ssl.storage_adapters.redis")
    auto_ssl:set("redis", {
      host = "redis-ssl.xxx2hl4.ng.0001.usw2.cache.amazonaws.com"
    })

    auto_ssl:set("allow_domain", function(domain)
      return true
    end)
    auto_ssl:init()
  }
```

Thing is, I can't tell if it's actually storing in the redis cache. (Yes, total n00b here). I've cleared everything from /storage and /certs, rebooted, and when I point a new domain to the server, the challenge is deployed and the cert is issued (yay). BUT, when I check /certs afterwards, the directory for the new domain is showing with the certs inside. **/file, however, is empy.**

Is this the expected behavior? 

And if I point a previously-issued domain to the server, the cert appears to be returned instantly, with no challenge generated/validated.

Were my previous certs copied to the redis cache? (currently trying to figure out what keys are in the cache...so I can see for myself!)

Thanks again for your help. Really appreciate it!

**Comment by bryanus** [comment]
Update: OK, I managed to see all of the keys in the Redis cache and all of my domains are in there! So I guess when I changed the storage adapter, the existing keys were copied over to it?

So my next assumption is that if the domain cert exists locally it uses that first, otherwise looks in the Redis cache, else generate a new cert?

If so, then I think it's WORKING??!! wow, coolness...

**Comment by bryanus** [comment]
Sorry to re-open this, but even though I have the Redis storage up and running perfectly, I am considering going back to local storage for the certificates due to cost concerns of running a dual-node Redis cluster on AWS.

So I'm back to my original questions, and a couple more if I may:

1) What would happen if a newly spawned server instance has an expired cert on it and a request for it comes in? Would the cert renew/reissue at that time or would the certificate show as expired in the user's browser? I assume the renewal cron would run that evening to renew any expiring/expired certs?

2) And when a renewal occurs, is the certificate extended for another 90 days from the original expiration date, or does it only add 60 days (since the renewal check occurs at 30 days before expiration)? I'm thinking I could conceivably image the server while the certs are still valid, and continue to re-image every 60/90 days/whenever, so that the certs in the current image are always current (I know, more manual work, but taking Redis out would save me a bunch of money!).

TIA.

**Comment by luto** [comment]
AWS offers a [managed redis solution](https://aws.amazon.com/elasticache/redis-details/), did you compare the pricing there? I have never used any AWS products personally, though.

1. it uses that certificate; only when the renew job runs, so yes, it would show a browser warning/error; yes
2. a renewed certificate is good for 90 days starting from the renewal date, afaik.

**Comment by bryanus** [comment]
Thanks Luto. Yes, I am already using the AWS Managed Redis service. Even with their lowest t2.micro cache, it comes to over $200/yr for a dual-node cluster with their Reserved Instance pricing. That's borderline too expensive for me based on my needs, plus I am new to Redis and concerned about how to gauge resources, etc.

So if a cert is renewed with 30 days left in the original certificate's expiration date, it adds 90 days from the date of renewal and not to the end of the original expiration? OK, I'll try to see if I can find a definitive answer to this and report back if it's not the case.

Thanks again!
