### ISSUE TITLE
Can someone review my openresty/nginx logrotate conf?

### ISSUE THREAD

**Issue by bryanus** [GUI/lua-resty-auto-ssl#153]
I've been trying to get the bottom of why my renewal process isn't running consistently every day, and I think I've narrowed it down to my logrotate config. In it, I have a postrotate block that reloads openresty.

````
/usr/local/openresty/nginx/logs/*.log {
	daily
	missingok
	rotate 30
	compress
	delaycompress
	notifempty
	create 0640 www-data adm
	sharedscripts
	prerotate
		if [ -d /etc/logrotate.d/httpd-prerotate ]; then \
			run-parts /etc/logrotate.d/httpd-prerotate; \
		fi \
	endscript
	postrotate
		service openresty reload >/dev/null 2>&1
	endscript
}
````

Thing is, I'm not sure where I got this config from when I first set up my server, and am also not sure if I need to reload openresty as part of the daily log rotation.

Is the reload required to run auto-ssl's renewal check? Based on my logs of when it does run, the timestamp coincides with the logrotation, so my assumption is that the restart is triggering the renewal script to run (but might also be interrupting it and causing it to be skipped on occasion).

I guess what I am trying to figure out is how the renewal process is kicked off and what triggers it.

Any suggestions would be appreciated! TIA.

**Comment by ruledio** [comment]
Looking at the code and wondering about this myself I think the renewal is kicked of on first load, your log rotation runs every 30 days and renewal check is every day, maybe the renewal check runs first and the logrotate then kills of this process leaving the renewal lock in place. 

Maybe try setting renewal to every 12 hours to avoid this.

**Comment by bryanus** [comment]
Thanks @ruledio for taking a look at my config.

My suspicion is pretty much the same as yours. That the renewal process starts to run, then logrotate either kills it (or my postrotate block reloads it, killing it).

If the renewal process is kicked off when openresty is re/loaded, then it seems that the postrotate block is what is kicking off the renewal check, as the timestamp in my logs when it does run matches when my logs are rotated by cron (@06:25AM UTC). 

Based on your suggestion, I've changed the auto-renewal setting to 12 hrs. But I am curious to know how the renewal process gets kicked off when changing the renewal interval. I am also wondering if checking too often has other consequences I may not be aware of.

**Comment by ruledio** [comment]
I'm certain during the worker init the renewal job is spawned after the sockproc process is started and runs on a loop as per the renew_check_interval setting.

Changing to 12 hours should not cause any issues I don't think just keep an eye on the logs.

**Comment by bryanus** [comment]
ok, so 12+ hours later and it looks like changing the interval kicked off the renewal process. Previously, my logs rotated (and renewal kicked off) at 06:25AM UTC, but changing the interval to 12 hours allowed the renewal to kick off at 18:25PM UTC, but _without_ the log rotation occurring at the same time.

Checking out my logs, I can see that the 18:25PM renewal process ran/completed. But looking at the  06:25AM one, **it did not**.

Here is my log at 06:25AM right at the beginning of the log rotation

````
2018/09/25 06:25:02 [notice] 20442#20442: signal 1 (SIGHUP) received from 22681, reconfiguring
2018/09/25 06:25:02 [notice] 20442#20442: reconfiguring
2018/09/25 06:25:02 [notice] 32509#32509: gracefully shutting down
2018/09/25 06:25:02 [notice] 32509#32509: exiting
2018/09/25 06:25:02 [notice] 32509#32509: exit
````

And here is the log once the new log was started:

````
2018/09/25 06:25:02 [notice] 15454#15454: signal process started
2018/09/25 06:25:02 [notice] 20442#20442: using the "epoll" event method
2018/09/25 06:25:02 [notice] 20442#20442: start worker processes
2018/09/25 06:25:02 [notice] 20442#20442: start worker process 15488
2018/09/25 06:25:02 [notice] 15488#15488: signal 17 (SIGCHLD) received from 15489
2018/09/25 06:25:02 [notice] 15488#15488: unknown process 15489 exited with code 0
2018/09/25 06:25:02 [notice] 15488#15488: signal 17 (SIGCHLD) received from 15493
2018/09/25 06:25:02 [notice] 15488#15488: unknown process 15493 exited with code 0
2018/09/25 06:25:02 [notice] 15488#15488: signal 17 (SIGCHLD) received from 15496
2018/09/25 06:25:02 [notice] 15488#15488: unknown process 15496 exited with code 0
2018/09/25 06:25:02 [notice] 15488#15488: signal 17 (SIGCHLD) received from 15499
2018/09/25 06:25:02 [notice] 15488#15488: unknown process 15499 exited with code 0
2018/09/25 06:25:02 [notice] 20442#20442: signal 17 (SIGCHLD) received from 15460
2018/09/25 06:25:02 [notice] 20442#20442: worker process 26023 exited with code 0
2018/09/25 06:25:02 [notice] 20442#20442: signal 29 (SIGIO) received
````

I do think something is killing the renewal process when the log rotates. Not sure what it is or how to fix it, but as long as it does run with the 12 hr interval setting, I'm happy.

Thanks again @ruledio !

**Comment by bryanus** [comment]
Just wanted to follow up and note that changing my interval to 12hours – in order to not run at the same time as my log rotation – seems to have done the trick. The renewal kicks off 1x/day, consistently, when a log rotation hasn't occurred simultaneously. When a log rotation does occur at the same time, the renewal check does not run. Not sure if it's expected behavior or a bug or my setup. Thanks again @ruledio!
