### ISSUE TITLE
Nginx not starting after replacing contents of nginx.conf

### ISSUE THREAD

**Issue by arya6000** [GUI/lua-resty-auto-ssl#163]
I tried installing lua-resty-auto-ssl on a fresh install of Debian 9

I did the following

```
apt update
apt install nginx
apt install build-essential
apt install luarocks
luarocks install lua-resty-auto-ssl
mkdir /etc/resty-auto-ssl
chown www-data /etc/resty-auto-ssl
```

I then replaced /etc/nginx/nginx.conf with the minimal example posted here in the read me https://github.com/GUI/lua-resty-auto-ssl

But after replacing the contents of ngix.conf with the minimal example, nginx can no longer start

I get

```
root@vultr:/etc/nginx# /etc/init.d/nginx start
[....] Starting nginx (via systemctl): nginx.serviceJob for nginx.service failed because the control process exited with error code.
See "systemctl status nginx.service" and "journalctl -xe" for details.
 failed!
root@vultr:/etc
```

```
root@vultr:/etc/nginx# systemctl status nginx.service
● nginx.service - A high performance web server and a reverse proxy server
   Loaded: loaded (/lib/systemd/system/nginx.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sat 2019-02-02 20:17:41 UTC; 50s ago
     Docs: man:nginx(8)
  Process: 6606 ExecStop=/sbin/start-stop-daemon --quiet --stop --retry QUIT/5 --pidfile /run/nginx.pid (code=exited, status=0/SUCCESS)
  Process: 483 ExecStart=/usr/sbin/nginx -g daemon on; master_process on; (code=exited, status=0/SUCCESS)
  Process: 6923 ExecStartPre=/usr/sbin/nginx -t -q -g daemon on; master_process on; (code=exited, status=1/FAILURE)
 Main PID: 496 (code=exited, status=0/SUCCESS)

Feb 02 20:17:41 vultr.guest systemd[1]: Starting A high performance web server and a reverse proxy server...
Feb 02 20:17:41 vultr.guest nginx[6923]: nginx: [emerg] unknown directive "lua_shared_dict" in /etc/nginx/nginx.conf:14
Feb 02 20:17:41 vultr.guest nginx[6923]: nginx: configuration file /etc/nginx/nginx.conf test failed
Feb 02 20:17:41 vultr.guest systemd[1]: nginx.service: Control process exited, code=exited status=1
Feb 02 20:17:41 vultr.guest systemd[1]: Failed to start A high performance web server and a reverse proxy server.
Feb 02 20:17:41 vultr.guest systemd[1]: nginx.service: Unit entered failed state.
Feb 02 20:17:41 vultr.guest systemd[1]: nginx.service: Failed with result 'exit-code'.
```

contents of my nginx.conf

```
user www-data;
worker_processes auto;
pid /run/nginx.pid;
include /etc/nginx/modules-enabled/*.conf;

events {
  worker_connections 1024;
}

http {
  # The "auto_ssl" shared dict should be defined with enough storage space to
  # hold your certificate data. 1MB of storage holds certificates for
  # approximately 100 separate domains.
  lua_shared_dict auto_ssl 1m;
  # The "auto_ssl_settings" shared dict is used to temporarily store various settings
  # like the secret used by the hook server on port 8999. Do not change or
  # omit it.
  lua_shared_dict auto_ssl_settings 64k;

  # A DNS resolver must be defined for OCSP stapling to function.
  #
  # This example uses Google's DNS server. You may want to use your system's
  # default DNS servers, which can be found in /etc/resolv.conf. If your network
  # is not IPv6 compatible, you may wish to disable IPv6 results by using the
  # "ipv6=off" flag (like "resolver 8.8.8.8 ipv6=off").
  resolver 8.8.8.8;

  # Initial setup tasks.
  init_by_lua_block {
    auto_ssl = (require "resty.auto-ssl").new()

    -- Define a function to determine which SNI domains to automatically handle
    -- and register new certificates for. Defaults to not allowing any domains,
    -- so this must be configured.
    auto_ssl:set("allow_domain", function(domain)
      return true
    end)

    auto_ssl:init()
  }

  init_worker_by_lua_block {
    auto_ssl:init_worker()
  }

  # HTTPS server
  server {
    listen 443 ssl;

    # Dynamic handler for issuing or returning certs for SNI domains.
    ssl_certificate_by_lua_block {
      auto_ssl:ssl_certificate()
    }

    # You must still define a static ssl_certificate file for nginx to start.
    #
    # You may generate a self-signed fallback with:
    #
    # openssl req -new -newkey rsa:2048 -days 3650 -nodes -x509 \
    #   -subj '/CN=sni-support-required-for-valid-ssl' \
    #   -keyout /etc/ssl/resty-auto-ssl-fallback.key \
    #   -out /etc/ssl/resty-auto-ssl-fallback.crt
    ssl_certificate /etc/ssl/resty-auto-ssl-fallback.crt;
    ssl_certificate_key /etc/ssl/resty-auto-ssl-fallback.key;
  }

  # HTTP server
  server {
    listen 80;

    # Endpoint used for performing domain verification with Let's Encrypt.
    location /.well-known/acme-challenge/ {
      content_by_lua_block {
        auto_ssl:challenge_server()
      }
    }
  }

  # Internal server running on port 8999 for handling certificate tasks.
  server {
    listen 127.0.0.1:8999;

    # Increase the body buffer size, to ensure the internal POSTs can always
    # parse the full POST contents into memory.
    client_body_buffer_size 128k;
    client_max_body_size 128k;

    location / {
      content_by_lua_block {
        auto_ssl:hook_server()
      }
    }
  }
}

```

Any idea what is wrong?

**Comment by gjongenelen** [comment]
Looks like nginx isn’t loading lua correctly.
Heres my dockerfile, based on ubuntu 16:04. Maybe it will help you out:
https://pastebin.com/dnENPEaM

**Comment by arya6000** [comment]
> Looks like nginx isn’t loading lua correctly.
> Heres my dockerfile, based on ubuntu 16:04. Maybe it will help you out:
> https://pastebin.com/dnENPEaM
> With the correct setup your config should work just fine

Thanks, I will manually run the commands in the file to install it. It's ok to install nginx using apt before everything else right?

**Comment by arya6000** [comment]
I started following your file, but don't understand what these lines do

```
ADD mime.types /etc/nginx/
ADD fastcgi_params /etc/nginx/
 
ADD ./start.sh /root/
```

**Comment by arya6000** [comment]
Unfortunately still no success. I did the following on a fresh install of Debian 9, this time I did not install Ngix but installed Openresty instead

```
apt update
apt upgrade
wget -qO - https://openresty.org/package/pubkey.gpg | apt-key add -
apt-get -y install software-properties-common
add-apt-repository -y "deb http://openresty.org/package/debian $(lsb_release -sc) openresty"
apt-get update
apt-get install openresty
apt install luarocks
apt install build-essential
luarocks install lua-resty-auto-ssl
mkdir /etc/resty-auto-ssl
chown www-data /etc/resty-auto-ssl
```


I then changed the contents of /etc/openresty/nginx.conf 

but I get the following after trying to start it

```
root@vultr:/etc/openresty# /etc/init.d/openresty start
[....] Starting openresty (via systemctl): openresty.serviceJob for openresty.service failed because the control process exited with error code.
See "systemctl status openresty.service" and "journalctl -xe" for details.
 failed!
```

**Comment by arya6000** [comment]
I got it to start by running

```
openssl req -new -newkey rsa:2048 -days 3650 -nodes -x509 -subj '/CN=sni-support-required-for-valid-ssl' \
> -keyout /etc/ssl/resty-auto-ssl-fallback.key -out /etc/ssl/resty-auto-ssl-fallback.crt
```

**Comment by arya6000** [comment]
Only issue I'm facing now is that if I go to https://mydomain.com the certificate is by "sni-support-required-for-valid-ssl" looks like it's not generating letsencrypt certificate for my domain.

**Comment by arya6000** [comment]
It's a permission issue. If I change nginx user to root everything works fine. I will find a way to fix it and then I will write a installation guide.

**Comment by arya6000** [comment]
Thanks for your help. I wrote a step by step guide for future reference 

[](http://forgezilla.com/installing-lua-resty-auto-ssl-on-debian-9/)

**Comment by OpsKunal** [comment]
Content of my nginx.conf

`user www-data;
worker_processes auto;
pid /run/nginx.pid;
# remote the escape char if you are going to use this config
include /etc/nginx/modules-enabled/\*.conf;

events {
  worker_connections 768;
}

http {

  # basic config
  sendfile on;
  tcp_nopush on;
  tcp_nodelay on;
  keepalive_timeout 65;
  types_hash_max_size 2048;
  include /etc/nginx/mime.types;
  default_type application/octet-stream;

  # ssl config
  ssl_protocols TLSv1 TLSv1.1 TLSv1.2; 
  ssl_prefer_server_ciphers on;

  # logging config
  log_format custom   '$remote_addr - $remote_user [$time_local] '
                      '"$request" $status $body_bytes_sent '
                      '"$http_referer" "$http_user_agent" "$http_x_forwarded_for"';

  access_log /var/log/nginx/access.log custom;
  error_log /var/log/nginx/error.log;

  # gzip
  gzip on;

  # virtual host config
  include /etc/nginx/conf.d/*.conf;
#  include /etc/nginx/sites-enabled/*;

  lua_shared_dict prometheus_metrics 10M;
  lua_package_path "/home/kunal/Documents/nginx-lua-prometheus/?.lua;;";
  init_worker_by_lua_block {
   prometheus = require("prometheus").init("prometheus_metrics")
   metric_requests = prometheus:counter(
   "nginx_http_requests_total", "Number of HTTP requests", {"host", "status"})
   metric_latency = prometheus:histogram(
   "nginx_http_request_duration_seconds", "HTTP request latency", {"host"})
   metric_connections = prometheus:gauge(
   "nginx_http_connections", "Number of HTTP connections", {"state"})
 }
  log_by_lua_block {
   metric_requests:inc(1, {ngx.var.server_name, ngx.var.status})
   metric_latency:observe(tonumber(ngx.var.request_time), {ngx.var.server_name})
 }
`

Any suggestion on what is wrong here?

**Comment by Jexah** [comment]
> Thanks for your help. I wrote a step by step guide for future reference
> 
> [Intalling lua resty auto ssl on Debian](http://forgezilla.com/installing-lua-resty-auto-ssl-on-debian-9)

Hey @arya6000,

I'm experiencing the same issues, but the link your posted is now broken :(

Reckon you could help me out?
