### ISSUE TITLE
Using Lua's string.find to block unwanted domains?

### ISSUE THREAD

**Issue by bryanus** [GUI/lua-resty-auto-ssl#170]
I know this is not best practice and I should be whitelisting instead of blacklisting, but it is quite a big project for me to develop a whitelist that would work for my platform.

So for now, I would like to block certificates by string matching. Is there a better, more efficient way to do this?

````

init_by_lua_block {
    auto_ssl = (require "resty.auto-ssl").new()
    auto_ssl:set("allow_domain", function(domain)

    if string.find(domain, 'webmail') then
      return false   
    elseif string.find(domain, 'shop') then
      return false
    elseif string.find(domain, 'store') then
      return false
    elseif string.find(domain, 'blog') then
      return false
    elseif string.find(domain, 'wordpress') then
      return false
    elseif string.find(domain, 'mx') then
      return false
    elseif string.find(domain, 'webstore') then
      return false
    elseif string.find(domain, 'forum') then
      return false
    elseif string.find(domain, 'zmail') then
      return false
    elseif string.find(domain, 'relay') then
      return false
    elseif string.find(domain, 'mail') then
      return false     
    else
      return true
    end

    end)
    auto_ssl:set("renew_check_interval", 86400)
    auto_ssl:init()
  }
````

**Comment by luto** [comment]
Using blacklisting instead of whitelisting allows anyone on this planet to make your server get certificates for arbitrary domain names. Depending on the type and number of requests to their API, you'll quickly run into rate limits and even manual blocking by them. You are also directly violating the [Subscriber Agreement](https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf) by doing so:

> By requesting, accepting, or using a Let’s Encrypt Certificate:
> * You warrant to ISRG that You are the legitimate registrant of the Internet domain name (...) or that You are the duly authorized agent of such registrant.

Please don't.

**Comment by bryanus** [comment]
OK @luto I understand. I will give Whitelisting a shot. But perhaps you can point me to some whitelisting examples or implementation ideas. I haven't been able to find much to guide me. I honestly don't know where to start.

Does the allow_domain function have the ability to do lookups in a database? Would that be resource heavy/slow? All of my allowed domains would be listed in a separate Postgres RDS instance, but I don't know how to access that from allow_domain or if that is the way the whitelist should be implemented?

Or should I generate a file that contains the whitelist (what format?) and have it be accessed/read by allow_domain? Would this whitelist file be stored in memory? And as new domains are added to the file, would I restart Openresty to then reload/cache the whitelist again?

As you can see, I'm a bit at a loss on how to implement a whitelist!

I also don't fully understand the example in allow_domain:

````
auto_ssl:set("allow_domain", function(domain, auto_ssl, ssl_options)
  return ngx.re.match(domain, "^(example.com|example.net)$", "ijo")
end)
````

Is that a Whitelist or Blacklist? Can that be modified to read from an external file or perform a DB lookup? How?

In any case, thank you for your continued help with my numerous 'issues'! I appreciate your time and insight.

**Comment by bryanus** [comment]
OK, I read the SSL Certificate Configuration and it mentions using a custom dehydrated configuration file located at (example): `/etc/resty-auto-ssl/letsencrypt/conf.d/custom.sh`

Looking at Dehydrated's config options, I see:

````
# File containing the list of domains to request certificates for (default: $BASEDIR/domains.txt)
#DOMAINS_TXT="${BASEDIR}/domains.txt"
````

I assume that is where my whitelist would go? one per line?

How do I tell allow_domain to look for that file? I assume I change allow_domain to 'return false'?

Does the whitelist get cached or is it checked for every request?

TIA.

**Comment by bryanus** [comment]
OK, I've generated a txt file with all of my whitelisted domains, and placed it into the default directory at /etc/resty-auto-ssl/domains.txt.

I also created a custom.sh file in /conf.d with the line:

`DOMAINS_TXT="${BASEDIR}/domains.txt"`

I then removed all of the string matching I was doing, but I don't know how to write a function to direct allow_domain to pull from my domains.txt file.

Any tips?

**Comment by bryanus** [comment]
Still giving it a go over here. I was able to cobble together a working whitelist with this Lua block:

````
init_by_lua_block {
    auto_ssl = (require "resty.auto-ssl").new()
    auto_ssl:set("allow_domain", function(domain)

-- reading from domains.txt and in testing

    local shell_execute = require "resty.auto-ssl.utils.shell_execute"
    local ngx_re = require "ngx.re"
    local status, output, err = shell_execute("cat /etc/resty-auto-ssl/domains.txt")

    if err then
      ngx.log(ngx.ERR, "allow_domain cat error: ", err)
    else
      local domains = ngx_re.split(output, "\n")
      for _, d in ipairs(domains) do
        if (domain == d) then
          return true
        end
      end
    end
    
    return false
    
    end)
    auto_ssl:set("renew_check_interval", 43200)
    auto_ssl:init()
  }
````

I had to explicitIy read my domains.txt file by shell; I couldn't figure out have it be read in by setting the value in my /conf.d/custom.sh file (`DOMAINS_TXT="${BASEDIR}/domains.txt`).

But so far this seems to be working. I'm seeing lots of 'domain not allowed' messages in the error logs (good!). 

Now I need to figure out a way to update the file as my users update their domains. I am also wondering about performance. Does every request check my domains.txt file or is the file cached on nginx reload?

I found your [example config](https://gist.github.com/luto/ff4c7ccd0b0c9c9a9fe8cde67179ed6a) to cache, but am still trying to understand it/implement it.

Any tips or suggestions would be appreciated. TIA.

**Comment by luto** [comment]
You're pretty close! :) Although I've never tried it, you may be able to read a file in lua [like so](https://stackoverflow.com/a/31857671/2486196) or [this shorter example](https://stackoverflow.com/a/24428699/2486196) is a openresty context. That should enable you to get rid of the shell call to `cat`.

> I had to explicitIy read my domains.txt file by shell; I couldn't figure out have it be read in by setting the value in my /conf.d/custom.sh file (`DOMAINS_TXT="${BASEDIR}/domains.txt`).

Dehydrated is fully managed by auto-ssl. There is no need to modify any of its config files sooo you're probably better off storing your list of domains in a custom location, if you're not already doing that.

> Does every request check my domains.txt file or is the file cached on nginx reload?

It happens on every request. So if you'd like some caching, you'll have to build it yourself at this point.
Depending on the number of requests you expect, you may also be fine without caching. The `cat` call is going to hit your operating systems read cache pretty fast. Additionally already established connections via TLS session resumption don't end up in that function. Caching the contents of that file seems cleaner, though.

> I found your [example config](https://gist.github.com/luto/ff4c7ccd0b0c9c9a9fe8cde67179ed6a) to cache, but am still trying to understand it/implement it.

It loads a list of domains on worker initialization, stores it for later [like documented by resty](https://github.com/openresty/lua-nginx-module#data-sharing-within-an-nginx-worker) and then checks for keys being present in `allow_domain()`. Feel free to ask any specific questions as comments to that gist!

**Comment by bryanus** [comment]
Thanks luto!

I did try the io.open method at first, but then I found [a comment by @GUI](https://github.com/GUI/lua-resty-auto-ssl/issues/59#issuecomment-294379418):

> Generally speaking, you'll want to try and avoid things like `io.popen` in OpenResty, since it's a blocking operation (so it will tie up the nginx worker process from serving other requests while it's executing). Internally we use [lua-resty-shell](https://github.com/juce/lua-resty-shell) to execute shell commands, which allows for a non-blocking approach to executing commands (it should also be handled more gracefully during nginx restarts).

That's why I used the shell command as in your example config.

> It happens on every request. So if you'd like some caching, you'll have to build it yourself at this point.
Depending on the number of requests you expect, you may also be fine without caching. The `cat` call is going to hit your operating systems read cache pretty fast.

Do you mean that the `cat` call will hit a read cache _limit_? Or do you mean it will be pretty fast/efficient? The number of requests is pretty low, IMO; I may not need caching as long as I'm not hitting some sort of limit.

I'll definitely give the caching a shot, but right now my next concern is how to update my whitelist dynamically, when a user updates it from my app. This is all pretty new to me, so it seems complicated!

But you're right, whitelisting was the way to go. I am seeing zero invalid certificate requests to LetsEncrypt now for bogus domains!

**Comment by luto** [comment]
> Generally speaking, you'll want to try and avoid things like `io.popen` in OpenResty, since it's a blocking operation (so it will tie up the nginx worker process from serving other requests while it's executing).

That's true! If you're doing it in `init_worker_by_lua_block` it would only block during startup, though. Doesn't seem too bad to me.

> Do you mean that the `cat` call will hit a read cache _limit_? Or do you mean it will be pretty fast/efficient?

The latter. Most operating systems come with "automatic" caching for reading from the disks. Assuming you have some RAM to spare, the file will end up in there and thus make cat pretty fast.

> But you're right, whitelisting was the way to go. I am seeing zero invalid certificate requests to LetsEncrypt now for bogus domains!

Great! :) Then I'll close this issue for now.
