### ISSUE TITLE
Want to know about generate auto ssl limit of lua-resty-auto-ssl

### ISSUE THREAD

**Issue by mehul-saleshandy** [GUI/lua-resty-auto-ssl#179]
Just I have installed and configure GUI/lua-resty-auto-ssl and its working fine! I want to know about the limit, how many certificate generate by lua-resty-auto-ssl? Any limit per day or week?

I am using ubuntu system and configured lua-resty-auto-ssl well, when I run the sub-domain(https://sub.domain.com) it is creating auto ssl for that sub-domain.

I want to know the limit, how many domain I can use per day or week for generate auto ssl using lua-resty-auto-ssl?

**Comment by gjongenelen** [comment]
This module is using Dehydrated to issue certificates from Let’s Encrypt. So you are limited by LE.
https://letsencrypt.org/docs/rate-limits/

**Comment by mehul-saleshandy** [comment]
Thanks. @gjongenelen
