### ISSUE TITLE
Some domains I don't want to renew, how can handle it?

### ISSUE THREAD

**Issue by mehul-saleshandy** [GUI/lua-resty-auto-ssl#181]
I don't want to renew some domains then what is the process ?
Can you please help me?

One more questions.
Some domains I want to remove, so it can not be used by lua-resty or should not renew in future?

**Comment by andreasschroth** [comment]
You should work with a whitelist of domains (e.g. Redis / text file based).

Then you remove those domains from the white list and they automatically won't be renewed in the future anymore and also the certificates won't be delivered to the clients anymore, thus SSL will stop working with those domains.

**Comment by mehul-saleshandy** [comment]
@andreasschroth Thanks for you reply.
Can you please help me for more details? How can manage whitelist of domains using text file based.
Please give me some instructions or steps for it or if possible then share some code example of it.

Thanks.

**Comment by andreasschroth** [comment]
@mehul-saleshandy Check the comments in this issue for example: https://github.com/GUI/lua-resty-auto-ssl/issues/170

There's some example code that should make it easy to implement it by yourself. And in the text file you just put one domain per line.

**Comment by GUI** [comment]
@mehul-saleshandy: I believe this should now be addressed in the new v0.13.0 release now that `allow_domain` is being called before renewals: https://github.com/GUI/lua-resty-auto-ssl/pull/176 So if you'd like for domains to no longer be renewed (after they're already registered), adjusting the logic of the `allow_domain` callback should ensure they no longer get renewed.

But let me know if you were looking for something else and we can reopen this.
