### ISSUE TITLE
missing ACMEv2 support: account creation / new domains will stop working soon

### ISSUE THREAD

**Issue by luto** [GUI/lua-resty-auto-ssl#189]
> Account creation on ACMEv1 is disabled. Please upgrade your ACME client to a version that supports ACMEv2 / RFC 8555. See https://community.letsencrypt.org/t/end-of-life-plan-for-acmev1/88430 for details.

**Comment by luto** [comment]
This currently breaks with the staging CA and will break in production starting November 2019.

**Comment by luto** [comment]
dehydrated has been supporting ACMEv2 for [more than a year now](https://github.com/lukas2511/dehydrated/issues/420), but [our version](https://github.com/lukas2511/dehydrated/commit/0bc0bd13d6abdc027c58bec12f7c2d3198d3a677) is older than that. Maybe an update does the trick?

**Comment by aviatrix** [comment]
@luto @GUI , from a quick glance of the changelog of dehydrated,  the api hasn't changed drastically and it should "just work".

**Comment by luto** [comment]
Thank you!
