### ISSUE TITLE
Using rediss (ssl wrapped redis) as storage_adapter

### ISSUE THREAD

**Issue by TrurlMcByte** [GUI/lua-resty-auto-ssl#191]
Any solution (excluding stunnel-like) for using ```rediss``` protocol (redis over ssl)?

**Comment by TrurlMcByte** [comment]
resty.redis have ```options_table``` optional argument, where possible to enable ssl 
https://github.com/openresty/lua-resty-redis#connect
But this argument not used in 
https://github.com/GUI/lua-resty-auto-ssl/blob/master/lib/resty/auto-ssl/storage_adapters/redis.lua#L39

**Comment by gjongenelen** [comment]
As far as I can see, making the following change would allow you to pass additional options to `redis:connect`
https://github.com/gjongenelen/lua-resty-auto-ssl/commit/ad94e4da191db51bc260b42866b3c660f8a759dd

**Comment by TrurlMcByte** [comment]
@gjongenelen Manually I did solution like this already, but it's "one-time-solutions", and next version may be incompatible with this changes.

**Comment by GUI** [comment]
In the new v0.13.0 release of lua-resty-auto-ssl, there's now support for passing `connect_options` to the redis configuration, which allows for configuring any of these connect options: https://github.com/GUI/lua-resty-auto-ssl#redis So this should be possible through something like:

```lua
auto_ssl:set("redis", {
  host = "10.10.10.1",
  connect_options = {
    ssl = true,
    ssl_verify = true,
  },
})
```

However, note that these SSL options only recently landed in lua-resty-redis's master (https://github.com/openresty/lua-resty-redis/pull/168), so these SSL specific options are not currently part of an official lua-resty-redis or OpenResty release. It should be part of lua-resty-redis's next release, but in the meantime, you'd need to install that module from master if you're looking to take advantage of this.
