### ISSUE TITLE
Missing requirement: curl

### ISSUE THREAD

**Issue by Eihrister** [GUI/lua-resty-auto-ssl#20]
Hi,

In the list of requirements, the "curl" commandline-tool is missing.
When you try to do the "luarocks install lua-resty-auto-ssl" on a minimalistic container, it fails on that not being available.

Daniël

**Comment by GUI** [comment]
Thanks for pointing this out. I've added an additional line about the other system dependencies (based on the dependencies letsencrypt.sh notes): https://github.com/GUI/lua-resty-auto-ssl/commit/c717f8343d4bb33a019a477b7b26431e4f7a4ada

There's also this somewhat related issue: https://github.com/GUI/lua-resty-auto-ssl/issues/19 It probably would be good for us to try and detect the dependencies at install or run time so we could provide a better error message. I'll try to get to that sometime this week.

**Comment by GUI** [comment]
In v0.9.0 there's now some better checking for dependencies during installation and at runtime.
