### ISSUE TITLE
continuing anyway - failed to get ocsp response: OCSP responder query failed (http://ocsp.int-x3.letsencrypt.org): ocsp.int-x3.letsencrypt.org could not be resolved (110: Operation timed out), context: ssl_certificate_by_lua*,

### ISSUE THREAD

**Issue by appunni-dishq** [GUI/lua-resty-auto-ssl#200]
SSL stopped working in between I am using https://github.com/Valian/docker-nginx-auto-ssl.

curl -6 -IL ocsp.int-x3.letsencrypt.org gives cannot connect to server . Normal curl is  working .

**Comment by kapouer** [comment]
```
curl -6 -IL ocsp.int-x3.letsencrypt.org
HTTP/1.1 200 OK
Server: nginx
Content-Length: 0
Cache-Control: max-age=25508
Expires: Wed, 06 Nov 2019 18:24:22 GMT
Date: Wed, 06 Nov 2019 11:19:14 GMT
Connection: keep-alive
```
your IPv6 setup is broken.

**Comment by appunni-dishq** [comment]
It was working fine, and suddenly stops working , I am using GCP to run the docker, tried setting resolver 127.0.0.53 ipv6=off. Still same error is coming.

**Comment by appunni-dishq** [comment]
; <<>> DiG 9.11.3-1ubuntu1.9-Ubuntu <<>> @8.8.8.8 ocsp.int-x3.letsencrypt.org
; (1 server found)
;; global options: +cmd
;; connection timed out; no servers could be reached

**Comment by appunni-dishq** [comment]
dig @2001:4860:4860::8888 ocsp.int-x3.letsencrypt.org AAAA

; <<>> DiG 9.11.3-1ubuntu1.9-Ubuntu <<>> @2001:4860:4860::8888 ocsp.int-x3.letsencrypt.org AAAA
; (1 server found)
;; global options: +cmd
;; connection timed out; no servers could be reached

**Comment by kapouer** [comment]
You just have a broken network... it's not up to this project maintainers to help you on this...
Can you resolve any other domain ? Can you check your docker runner has not shut off the DNS port  somehow ?

**Comment by appunni-dishq** [comment]
I am not able to resolve it using 8.8.8.8 but able to when i used 127.0.0.53
dig @127.0.0.53 ocsp.int-x3.letsencrypt.org

; <<>> DiG 9.11.3-1ubuntu1.9-Ubuntu <<>> @127.0.0.53 ocsp.int-x3.letsencrypt.org
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 33083
;; flags: qr rd ra; QUERY: 1, ANSWER: 5, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;ocsp.int-x3.letsencrypt.org.	IN	A

;; ANSWER SECTION:
ocsp.int-x3.letsencrypt.org. 1156 IN	CNAME	ocsp.int-x3.letsencrypt.org.edgesuite.net.
ocsp.int-x3.letsencrypt.org.edgesuite.net. 5550	IN CNAME a771.dscq.akamai.net.
a771.dscq.akamai.net.	19	IN	A	23.48.39.49
a771.dscq.akamai.net.	19	IN	A	23.48.39.51
a771.dscq.akamai.net.	19	IN	A	23.48.39.10

;; Query time: 19 msec
;; SERVER: 127.0.0.53#53(127.0.0.53)
;; WHEN: Wed Nov 06 12:00:10 UTC 2019
;; MSG SIZE  rcvd: 190

**Comment by appunni-dishq** [comment]
I think I figured it out, GCP has issues with using `8.8.8.8` as DNS resolution. And I have to manually specify `resolver 127.0.0.53 ipv6=off;` in nginx.conf http section.

**Comment by appunni-dishq** [comment]
https://github.com/Valian/docker-nginx-auto-ssl/issues/32 Solved the issue. Thanks for the help. It was definitely a network mishap from GCP I guess.
