### ISSUE TITLE
lua-resty-auto-ssl does not work when using TLS 1.3 0-RTT (ssl_early_data)

### ISSUE THREAD

**Issue by gohai** [GUI/lua-resty-auto-ssl#210]
I've built packages for `openresty-openssl-1.1.1d`, as well as `openresty-1.15.8.2` against that (happy to share if anyone's interested - for CentOS/RHEL 8).

With this TLS 1.3 using `lua-resty-auto-ssl` works just fine - however when I try to enable the 0-RTT mode by setting the [ssl_early_data](http://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl_early_data) option, it doesn't work any longer (in browser, and SSL Labs).

Is this an inherent limitation in how `lua-resty-auto-ssl` works, or is this a bug?

I've found https://github.com/openresty/lua-nginx-module/commit/d3dbc0c8102a9978d649c99e3261d93aac547378, which describes some complications with TLS 1.3 - but not specifically 0-RTT.

@spacewander @thibaultcha Any thoughts on this one? (`lua-resty-auto-ssl` uses `ssl_certificate_by_lua`. I believe the 1.15.8.2 version I was building came with `ngx_lua-0.10.15`.)

**Comment by spacewander** [comment]
Maybe you can apply the https://github.com/openresty/openresty/commit/34918a30c3fd19fe0ae9fabbbea442fef32e1118
There are several changes to support OpenSSL 1.1.1.
I think it would be better if you can try the master branch of https://github.com/openresty/openresty.

**Comment by gohai** [comment]
Thank you @spacewander - it was probably this missing patch.

From reading https://github.com/openresty/openresty/issues/456 I thought that adding TLS 1.3 to 1.15.8.2 is just a matter of using OpenSSL 1.1.1. But now I believe that I probably have to wait for the release after 1.15.8.2 for all the needed changes?

Anyway, not a bug.
