### ISSUE TITLE
Load-balanced and file sharing

### ISSUE THREAD

**Issue by fhorlaville** [GUI/lua-resty-auto-ssl#22]
Hi, if the config directory is on an NFS shared volume, can one still use files for storing config and certificates or will that not work?
Thanks!

**Comment by Eihrister** [comment]
It's not built to be NFS-aware, so if there's any network-hickups, trying to access a certificate/key pair from the storage backend, will fail and possibly lead to weird timeout-related things. But with NFS, that's with a lot of things.

That being said, it should work just fine.:

- Latency with requests shouldn't be an issue: They're cached inside a shared dict in nginx, as well.
- Multiple instances trying to issue the same cert should also not be an issue: Locking-mechanisms are in place.

How things will react with NFS-locks remains to be seen, I'm guessing you'll just get an error in your log.

**Comment by fhorlaville** [comment]
Thank you very much !!
I'm going to try it with our Gluster share and will report

**Comment by GUI** [comment]
Thanks, @Eihrister, for the detailed response! I'm going to go ahead and close this, but feel free to chime in if there's still any other questions or comments about this.
