### ISSUE TITLE
After Installation on Ubuntu 20.04. I am getting following error message to start openresty service

### ISSUE THREAD

**Issue by securewebsite** [GUI/lua-resty-auto-ssl#261]
ul 21 19:07:09 abto nginx[5215]:         no file '/usr/local/openresty/site/lualib/resty/auto-ssl/init.ljbc'
Jul 21 19:07:09 abto nginx[5215]:         no file '/usr/local/openresty/lualib/resty/auto-ssl.ljbc'
Jul 21 19:07:09 abto nginx[5215]:         no file '/usr/local/openresty/lualib/resty/auto-ssl/init.ljbc'
Jul 21 19:07:09 abto nginx[5215]:         no file '/usr/local/openresty/site/lualib/resty/auto-ssl.lua'
Jul 21 19:07:09 abto nginx[5215]:         no file '/usr/local/openresty/site/lualib/resty/auto-ssl/init.lua'
Jul 21 19:07:09 abto nginx[5215]:         no file '/usr/local/openresty/lualib/resty/auto-ssl.lua'
Jul 21 19:07:09 abto nginx[5215]:         no file '/usr/local/openresty/lualib/resty/auto-ssl/init.lua'
Jul 21 19:07:09 abto nginx[5215]:         no file './resty/auto-ssl.lua'
Jul 21 19:07:09 abto nginx[5215]:         no file '/usr/local/openresty/luajit/share/luajit-2.1.0-beta3/resty/auto-ssl.lua'
Jul 21 19:07:09 abto nginx[5215]:         no file '/usr/local/share/lua/5.1/resty/auto-ssl.lua'
Jul 21 19:07:09 abto nginx[5215]:         no file '/usr/local/share/lua/5.1/resty/auto-ssl/init.lua'
Jul 21 19:07:09 abto nginx[5215]:         no file '/usr/local/openresty/luajit/share/lua/5.1/resty/auto-ssl.lua'
Jul 21 19:07:09 abto nginx[5215]:         no file '/usr/local/openresty/luajit/share/lua/5.1/resty/auto-ssl/init.lua'
Jul 21 19:07:09 abto nginx[5215]:         no file '/usr/local/openresty/site/lualib/resty/auto-ssl.so'
Jul 21 19:07:09 abto nginx[5215]:         no file '/usr/local/openresty/lualib/resty/auto-ssl.so'
Jul 21 19:07:09 abto nginx[5215]:         no file './resty/auto-ssl.so'
Jul 21 19:07:09 abto nginx[5215]:         no file '/usr/local/lib/lua/5.1/resty/auto-ssl.so'
Jul 21 19:07:09 abto nginx[5215]:         no file '/usr/local/openresty/luajit/lib/lua/5.1/resty/auto-ssl.so'
Jul 21 19:07:09 abto nginx[5215]:         no file '/usr/local/lib/lua/5.1/loadall.so'
Jul 21 19:07:09 abto nginx[5215]:         no file '/usr/local/openresty/site/lualib/resty.so'
Jul 21 19:07:09 abto nginx[5215]:         no file '/usr/local/openresty/lualib/resty.so'
Jul 21 19:07:09 abto nginx[5215]:         no file './resty.so'
Jul 21 19:07:09 abto nginx[5215]:         no file '/usr/local/lib/lua/5.1/resty.so'
Jul 21 19:07:09 abto nginx[5215]:         no file '/usr/local/openresty/luajit/lib/lua/5.1/resty.so'
Jul 21 19:07:09 abto nginx[5215]:         no file '/usr/local/lib/lua/5.1/loadall.so'
Jul 21 19:07:09 abto nginx[5215]: stack traceback:
Jul 21 19:07:09 abto nginx[5215]:         [C]: in function 'require'
Jul 21 19:07:09 abto nginx[5215]:         init_by_lua:2: in main chunk

Which file should I change to give proper path of files?

**Comment by securewebsite** [comment]
this is more information

nginx: [error] init_by_lua error: init_by_lua:2: module 'resty.auto-ssl' not found:
	no field package.preload['resty.auto-ssl']
	no file '/usr/local/openresty/site/lualib/resty/auto-ssl.ljbc'
	no file '/usr/local/openresty/site/lualib/resty/auto-ssl/init.ljbc'
	no file '/usr/local/openresty/lualib/resty/auto-ssl.ljbc'
	no file '/usr/local/openresty/lualib/resty/auto-ssl/init.ljbc'
	no file '/usr/local/openresty/site/lualib/resty/auto-ssl.lua'
	no file '/usr/local/openresty/site/lualib/resty/auto-ssl/init.lua'
	no file '/usr/local/openresty/lualib/resty/auto-ssl.lua'
	no file '/usr/local/openresty/lualib/resty/auto-ssl/init.lua'
	no file './resty/auto-ssl.lua'
	no file '/usr/local/openresty/luajit/share/luajit-2.1.0-beta3/resty/auto-ssl.lua'
	no file '/usr/local/share/lua/5.1/resty/auto-ssl.lua'
	no file '/usr/local/share/lua/5.1/resty/auto-ssl/init.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/resty/auto-ssl.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/resty/auto-ssl/init.lua'
	no file '/usr/local/openresty/site/lualib/resty/auto-ssl.so'
	no file '/usr/local/openresty/lualib/resty/auto-ssl.so'
	no file './resty/auto-ssl.so'
	no file '/usr/local/lib/lua/5.1/resty/auto-ssl.so'
	no file '/usr/local/openresty/luajit/lib/lua/5.1/resty/auto-ssl.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file '/usr/local/openresty/site/lualib/resty.so'
	no file '/usr/local/openresty/lualib/resty.so'
	no file './resty.so'
	no file '/usr/local/lib/lua/5.1/resty.so'
	no file '/usr/local/openresty/luajit/lib/lua/5.1/resty.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
	[C]: in function 'require'
	init_by_lua:2: in main chunk

**Comment by securewebsite** [comment]
After reinstallation I am getting following error message

/usr/local/lib/luarocks/rocks# luarocks install lua-resty-auto-ssl
Installing https://luarocks.org/lua-resty-auto-ssl-0.13.1-1.src.rock
sh: 1: make: not found

Error: Build error: Failed building.

**Comment by securewebsite** [comment]
Jul 22 11:54:20 abto nginx[31287]:         no field package.preload['resty.auto-ssl']
Jul 22 11:54:20 abto nginx[31287]:         no file '/usr/local/openresty/site/lualib/resty/auto-ssl.ljbc'
Jul 22 11:54:20 abto nginx[31287]:         no file '/usr/local/openresty/site/lualib/resty/auto-ssl/init.ljbc'
Jul 22 11:54:20 abto nginx[31287]:         no file '/usr/local/openresty/lualib/resty/auto-ssl.ljbc'
Jul 22 11:54:20 abto nginx[31287]:         no file '/usr/local/openresty/lualib/resty/auto-ssl/init.ljbc'
Jul 22 11:54:20 abto nginx[31287]:         no file '/usr/local/openresty/site/lualib/resty/auto-ssl.lua'
Jul 22 11:54:20 abto nginx[31287]:         no file '/usr/local/openresty/site/lualib/resty/auto-ssl/init.lua'
Jul 22 11:54:20 abto nginx[31287]:         no file '/usr/local/openresty/lualib/resty/auto-ssl.lua'
Jul 22 11:54:20 abto nginx[31287]:         no file '/usr/local/openresty/lualib/resty/auto-ssl/init.lua'
Jul 22 11:54:20 abto nginx[31287]:         no file './resty/auto-ssl.lua'
Jul 22 11:54:20 abto nginx[31287]:         no file '/usr/local/openresty/luajit/share/luajit-2.1.0-beta3/resty/auto-ssl.lua'
Jul 22 11:54:20 abto nginx[31287]:         no file '/usr/local/share/lua/5.1/resty/auto-ssl.lua'
Jul 22 11:54:20 abto nginx[31287]:         no file '/usr/local/share/lua/5.1/resty/auto-ssl/init.lua'
Jul 22 11:54:20 abto nginx[31287]:         no file '/usr/local/openresty/luajit/share/lua/5.1/resty/auto-ssl.lua'
Jul 22 11:54:20 abto nginx[31287]:         no file '/usr/local/openresty/luajit/share/lua/5.1/resty/auto-ssl/init.lua'
Jul 22 11:54:20 abto nginx[31287]:         no file '/usr/local/openresty/site/lualib/resty/auto-ssl.so'
Jul 22 11:54:20 abto nginx[31287]:         no file '/usr/local/openresty/lualib/resty/auto-ssl.so'
Jul 22 11:54:20 abto nginx[31287]:         no file './resty/auto-ssl.so'
Jul 22 11:54:20 abto nginx[31287]:         no file '/usr/local/lib/lua/5.1/resty/auto-ssl.so'
Jul 22 11:54:20 abto nginx[31287]:         no file '/usr/local/openresty/luajit/lib/lua/5.1/resty/auto-ssl.so'
Jul 22 11:54:20 abto nginx[31287]:         no file '/usr/local/lib/lua/5.1/loadall.so'
Jul 22 11:54:20 abto nginx[31287]:         no file '/usr/local/openresty/site/lualib/resty.so'
Jul 22 11:54:20 abto nginx[31287]:         no file '/usr/local/openresty/lualib/resty.so'
Jul 22 11:54:20 abto nginx[31287]:         no file './resty.so'
Jul 22 11:54:20 abto nginx[31287]:         no file '/usr/local/lib/lua/5.1/resty.so'
Jul 22 11:54:20 abto nginx[31287]:         no file '/usr/local/openresty/luajit/lib/lua/5.1/resty.so'
Jul 22 11:54:20 abto nginx[31287]:         no file '/usr/local/lib/lua/5.1/loadall.so'
Jul 22 11:54:20 abto nginx[31287]: stack traceback:
Jul 22 11:54:20 abto nginx[31287]:         [C]: in function 'require'
Jul 22 11:54:20 abto nginx[31287]:         init_by_lua:2: in main chunk
Jul 22 11:54:20 abto systemd[1]: openresty.service: Control process exited, code=exited, status=1/FAILURE

**Comment by securewebsite** [comment]
Issue has been solved now. I have to add lua_package_path in nginx.conf to resolve the issue. Thanks :)

**Comment by steamboy** [comment]
> After reinstallation I am getting following error message
> 
> /usr/local/lib/luarocks/rocks# luarocks install lua-resty-auto-ssl
> Installing https://luarocks.org/lua-resty-auto-ssl-0.13.1-1.src.rock
> sh: 1: make: not found
> 
> Error: Build error: Failed building.

I'm currently getting this on a fresh install, were you able to get this working?
