### ISSUE TITLE
Please mention ssl patch for nginx in documentation

### ISSUE THREAD

**Issue by non7top** [GUI/lua-resty-auto-ssl#30]
Please update the documentation to mention that vanilla nginx will require patch and this lua package will not work without it.

https://raw.githubusercontent.com/openresty/openresty/dbccee1418ddb24a2adabd80b0737595b7fd577e/patches/nginx-1.11.2-ssl_cert_cb_yield.patch

**Comment by GUI** [comment]
Thanks for pointing that out! The README has been updated.
