### ISSUE TITLE
Redis connection config for cluster?

### ISSUE THREAD

**Issue by waynerobinson** [GUI/lua-resty-auto-ssl#39]
How do I specify multiple cluster nodes to connect to for the Redis config?

**Comment by GUI** [comment]
Unfortunately, it looks like lua-resty-redis doesn't yet support Redis Cluster: https://github.com/openresty/lua-resty-redis/issues/102 So I'm not sure we can do much to support Redis Cluster until support lands in lua-resty-redis.

**Comment by GUI** [comment]
I'm going go go ahead and close this, since there's not much we can do about cluster support within this project right now. But if lua-resty-redis gains support for it, we can certainly revisit.
