### ISSUE TITLE
Storage dirs are created with wrong user

### ISSUE THREAD

**Issue by ashb** [GUI/lua-resty-auto-ssl#4]
The instructions on the readme say create `/etc/resty-auto-ssl/` and chown it to the nginx user, but the files that `auto_ssl:init()` creates are owned by root, not the `user` directive in the config file -- this means I get this error:

```
2016/04/03 18:43:00 [error] 16#16: [lua] ssl_certificate.lua:55: issue_cert(): auto-ssl: failed to obtain lock: /etc/resty-auto-ssl/storage/file/test.ignoreme.com%3Aissue_cert_lock:
 Permission denied, context: ssl_certificate_by_lua*, client: 127.0.0.1, server: 0.0.0.0:443```

**Comment by GUI** [comment]
Thanks for finding this. I believe this should be fixed for fresh installations with the latest commit: https://github.com/GUI/lua-resty-auto-ssl/commit/6fc36d804a575c81a54537643b5796b1ab23c391

To fix an existing installation, I think there are two primary options:

1. Manually fix the permissions on the storage directory: `sudo chown -R www-data /etc/resty-auto-ssl/storage` (or use whichever user you run nginx as).
2. If you updated to the latest version of lua-resty-auto-ssl from master, you could then blow away the storage directory, and it should be re-created with the proper permissions after restarting nginx (but only do this if you don't care about what's currently in storage): `sudo rm -r /etc/resty-auto-ssl/storage`

Let me know if you're still having any troubles, though.

**Comment by ashb** [comment]
Thanks! I'll give it a go.

(I managed to fix it by chowning as you suggest, I just want to leave things reproduce-able.)
