### ISSUE TITLE
Lower OpenSSL version requirement?

### ISSUE THREAD

**Issue by gdubicki** [GUI/lua-resty-auto-ssl#40]
Hi,

I tried to use your solution on Ubuntu 12.04 but I had a problem with OpenSSL as 1.0.2e is not available in that distro release and building from source got me into more trouble. But if https://ma.ttias.be/day-google-chrome-disables-http2-nearly-everyone-may-31st-2016/ is still valid, then actually lua-resty-auto-ssl is useful only on Ubuntu 16.04, among the most popular "pro" distros. Is that right? Anyway: can you please lower the requirements for OpenSSL to, let's say, 1.0.1?

**Comment by GUI** [comment]
Openssl 1.0.2e is required for this feature to work in OpenResty (see [ssl_certificate_by_lua_block](https://github.com/openresty/lua-nginx-module/#ssl_certificate_by_lua_block)'s "one needs at least OpenSSL 1.0.2e for this directive to work" note).

That being said, I usually haven't had any issues using newer versions of OpenSSL on older Linux distros with nginx (including Ubuntu 12.04). Note that you don't need to try and install the newer version of OpenSSL in a system-wide fashion (which might lead to issues), but instead you can just compile OpenResty/nginx against the newer version of OpenSSL (and you don't actually need to build OpenSSL, you just need to point nginx to the source directory). So something like:

```sh
$ curl -OL "https://www.openssl.org/source/openssl-1.0.2j.tar.gz"
$ tar -xf openssl-1.0.2j.tar.gz
$ curl -OL "https://github.com/openresty/openresty/releases/download/v1.11.2.2/openresty-1.11.2.2.tar.gz"
$ tar -xf openresty-1.11.2.2.tar.gz
$ cd openresty-1.11.2.2
$ ./configure --with-openssl=../openssl-1.0.2j
$ make && sudo make install
```

If that makes sense and does the trick, I can try to update the README to clarify this OpenSSL requirement.
