### ISSUE TITLE
rsa 2048

### ISSUE THREAD

**Issue by Dejfik** [GUI/lua-resty-auto-ssl#41]
Hi,
i am currently using lua-resty-auto-ssl, it´s working like a charm, thank you.
I just noticed, that it´s generating 4096bits keys and i would like it to be 2048 keys (in opnenssl.cnf i have 2048 as default). I´ve looked through config files, but I haven´t found where should i set this.
Can you help me ?
Thanks

**Comment by GUI** [comment]
This default comes from [dehydrated](https://github.com/lukas2511/dehydrated), the Let's Encrypt client we use internally. You should be able to override more advanced dehydrated settings with any `.sh` files placed inside `/etc/resty-auto-ssl/letsencrypt/conf.d/`.

So in this case, I think if you created something like `/etc/resty-auto-ssl/letsencrypt/conf.d/custom.sh` with:

```sh
KEYSIZE="2048"
```

That should impact the key size used for any new certificates or renewals.

If that works for you, we can add some more general documentation about using this approach to override these dehydrated settings to our README.

**Comment by Dejfik** [comment]
Thank you for your reply. I added custom.sh file with KEYSIZE="2048" in it. I will let you know, when we make new certificate or renew old one, if this solution worked.

**Comment by Dejfik** [comment]
Hi, we recently created key for new website, but unfortunatelly the key size is still 4096, even though i followed your instructions. Do you have any other suggestions?
Thanks

**Comment by Dejfik** [comment]
Hi,
today i have been solving other issues with our lua-resty-auto ssl and i came over this by accident from logs that reported warning, that entirely defferent path /remote/machine/some/path/resty-auto.ssl/letsencrypt/conf.d directory is empty. I figured out that our openresty nginx takes conf files from other location. What a silly mistake. But it is working now, i created the faile containing KEYSIZE="2048" in the correct directory and it generates keys of that size. You can now close this issue as solved, thank you for your time and help.

**Comment by GUI** [comment]
Thanks for confirming that worked. I've added documentation about customizing the dehydrated config: https://github.com/GUI/lua-resty-auto-ssl#advanced-lets-encrypt-configuration
