### ISSUE TITLE
are any multi-subdomain servers actually using this in production?

### ISSUE THREAD

**Issue by DtpEJsaYXDU4GDH8dE4MyI9VrieF0UZpPZ0K76K** [GUI/lua-resty-auto-ssl#44]
are any multi-subdomain servers actually using this in production? seems unlikely

**Comment by gjongenelen** [comment]
Yes, we are!
~60 nodes + redis storage

No problems at all

**Comment by GUI** [comment]
Yup, we're also using this in production for various domains and subdomains. I'm going to close this, but feel free to open a new issue if you have a specific question.
