### ISSUE TITLE
Ability to provide email to register certificates against

### ISSUE THREAD

**Issue by brendon** [GUI/lua-resty-auto-ssl#46]
I'm wondering if there's a way to provide the email address that Let's Encrypt requires for registering domains?

**Comment by GUI** [comment]
Yes, this should be possible using a custom dehydrated config file. I've added documentation about how to do that: https://github.com/GUI/lua-resty-auto-ssl#advanced-lets-encrypt-configuration But let me know if that doesn't work for you.

**Comment by brendon** [comment]
Thanks @GUI :) That's very helpful. I'll give it a whirl and see how it goes.
