### ISSUE TITLE
Subdomain combination for easing rate limits

### ISSUE THREAD

**Issue by jackmiller334** [GUI/lua-resty-auto-ssl#49]
To be clear, this is a question rather than an issue. I apologise in advance if this is the incorrect place to ask questions regarding this plugin. 

I was reading over the rate limit documentation at Let's Encrypt and noticed this.

> If you have a lot of subdomains, you may want to combine them into a single certificate, up to a limit of 100 Names per Certificate. Combined with the above limit, that means you can issue certificates containing up to 2,000 unique subdomains per week. A certificate with multiple names is often called a SAN certificate, or sometimes a UCC certificate.

Does this plug in support this?

My goal to achieve is to have lots of subdomains pointed at a single server running nginx and this plugin. 

Thank you for your time.

**Comment by GUI** [comment]
We don't currently implement combined certificates, but it should be possible. This has come up previously in #36, so I'm going to close this issue in favor of that existing one, but happy to continue the conversation there.
