### ISSUE TITLE
Load balancer potential problems?

### ISSUE THREAD

**Issue by domharrington** [GUI/lua-resty-auto-ssl#58]
We have this running behind a load balancer with 2 servers: A and B. If an unknown domain makes a request to server A and it's valid, our server makes a new cert request to lets encrypt.

The next step is for lets encrypt to make a request back to us to confirm we are who we say we are. If the load balancer chooses to send that request to server B, then the confirmation will fail as it doesnt know about the pending domains.

Has anyone tackled this problem before? Are the pending domains stored in memory? Would it be possible to store this state in redis so that both servers could know about pending domains?

**Comment by GUI** [comment]
As long as you're using a storage adapter that's shared between servers (like the supplied Redis adapter), then this should already be taken care of. See the `storage_adapter` part of the [configuration](https://github.com/GUI/lua-resty-auto-ssl#configuration).

When using Redis, then the data is shared between the servers, so the issuance should work regardless of which underlying server Let's Encrypt hits during the challenge phase. We also use the configured storage adapter to try and prevent duplicate certs for the same domain from being registered if both servers are being hit simultaneously before the cert is issued.

But give a shout if you're seeing any issues with the current implementation, or have any other questions.

**Comment by domharrington** [comment]
Thanks for confirmation! I will upgrade the version to see if that resolves some of my issues.

**Comment by bardouni** [comment]
We still have this problem when Redis storage adapter is not possible,
I faced this problem when using Aws global accelerator with instances from europ and usa, Redis cannot be used in this case.
