### ISSUE TITLE
Cancel signing request with IP instead of Domain

### ISSUE THREAD

**Issue by gjongenelen** [GUI/lua-resty-auto-ssl#61]
Sometimes I see errors in my logs with a failed domain signing request
`"detail": "Error creating new authz :: Issuance for IP addresses not supported"`

Could you make a check on the beginning of the sequence to check wether it's a domain or IP, and cancel the sequence when it is a IP-address? Just to beautify the logs.

**Comment by luto** [comment]
Thanks for you suggestion. We've already got an issue covering it: https://github.com/GUI/lua-resty-auto-ssl/issues/26

@GUI or @gjongenelen please close this :)

**Comment by luto** [comment]
@GUI since we've already got an issue covering this, would you mind closing this one, please? :) I messed up your highlight in the last comment :sweat_smile:
