### ISSUE TITLE
Is it possible to combine multiple subdomains in a single certificate?

### ISSUE THREAD

**Issue by brickcap** [GUI/lua-resty-auto-ssl#62]
Hi,

certbot offers a functionality with which you can create a single certificate for multiple subdomains using a command like this:- 

`certbot-auto -d one.example.com -d two.example.com -d three.example.com -d example.org` 

Can we do the same with lua-resty-auto-ssl? Or does it create a different certificate for each of the sub-domains? 

PS: It seems that [dehydrated](https://github.com/lukas2511/dehydrated) also offers a `-d` flag:- 

> --domain (-d) domain.tld         Use specified domain name(s) instead of domains.txt entry (one certificate!)   

Thanks,
Akshat

**Comment by luto** [comment]
@brickcap not yet, but maybe soon! :) See https://github.com/GUI/lua-resty-auto-ssl/issues/36 and https://github.com/GUI/lua-resty-auto-ssl/pull/57.
@GUI or @brickcap please close this, as we've got an issue already.
