### ISSUE TITLE
Nginx stops routing requests to Passenger

### ISSUE THREAD

**Issue by kurttomlinson** [GUI/lua-resty-auto-ssl#63]
In production, my Rails app has many many subdomains that each need their own TLS cert. This causes lua-resty-auto-ssl to be constantly rate-limited by Let's Encrypt. That's not a problem except that eventually (after several hours), lua-resty-auto-ssl causes nginx to stop routing requests to Passenger.

I've uploaded the OpenResty debug and access logs to <https://kurttomlinson.com/files/nginx_logs_2017-4-49.zip>. Ignore any certificate errors you get when you try to download it. I've turned TLS off for the time being.

When I open `top` after nginx has stopped routing requests to Passenger, I see a lot of processes like these:
```
# about ten of these:
curl --silent --show-errors --fail -XPOST --header X-Hook-Secret: ... --data-urlencode domain=...
# about eleven of these:
bash /opt/openresty/luajit/bin/resty-auto-ssl/dehydrated --cron --no-lock --domain ...
# and about four of these:
openssl genrsa -out /etc/resty-auto-ssl/letsencrypt/certs/.../privkey-....pem4096
```

It seems that these processes are getting started by lua-resty-auto-ssl, failing, and never getting killed.

Passenger version 5.1.2.
OpenResty version 1.11.2.2.
lua-resty-auto-ssl version 0.10.6-1.
lua-rest-http version 0.10-0.

**Comment by luto** [comment]
Thanks for you bug report. Would you mind capturing the process tree using `ps fw` so we can see at which sub-task each of the dehydrated-clients has stopped on? Feel free to remove any unrelated processes or censor any secrets. Thank you!

**Comment by luto** [comment]
Closing this issue as we're still waiting for feedback. In case this is still an active topic for you, please just reopen it and we'll gladly take a look.
