### ISSUE TITLE
api requests can exceed client_body_buffer_size, which makes the hooks fail

### ISSUE THREAD

**Issue by luto** [GUI/lua-resty-auto-ssl#65]
In some cases the request size of hook POST requests can exceed the default `client_body_buffer_size` (16k). This causes nginx to buffer the request in a file, instead of in memory. Since [lua-nginx](https://github.com/openresty/lua-nginx-module/blob/master/src/ngx_http_lua_args.c#L185-L187) does not support temp files (yet?) the hooks fail.

A quick fix is increasing the `client_body_buffer_size` as well as `client_max_body_size`.

**Comment by GUI** [comment]
Interesting, I wonder why sometimes the request size is bigger (I don't think I've run into this personally), but definitely good to know about.

I can incorporate this into the suggested configuration in the README, and also see if there's maybe a way for us to check this on startup and warn users if their configuration needs to be updated.

Thanks again!

**Comment by luto** [comment]
We should be able to catch the error [when we call `get_post_args()`](https://github.com/GUI/lua-resty-auto-ssl/blob/master/lib/resty/auto-ssl/servers/hook.lua#L9). That's not at startup, but at least it gives some kind of message to the user.

We do not know beforehand how big the requests will be. This means, we can only print a generic warning on startup, when `client_body_buffer_size` is set to or near the default value. Buuut that value can of course be different for every `server` or even `location`, so we'd have to find the right one for our internal server first. Hm.

Unless you know some clever way to get the config, I'd vote for just noting this in the README as well as in the example configuration.

**Comment by GUI** [comment]
I updated the documentation (https://github.com/GUI/lua-resty-auto-ssl/pull/77), and made this part of the recommended v0.11.0 upgrade. Thanks for reporting this!

**Comment by luto** [comment]
Looks nice. Thank you! This should make the API server more robust :+1:
