### ISSUE TITLE
Restarting nginx clears certificates stored on disk

### ISSUE THREAD

**Issue by jackmiller334** [GUI/lua-resty-auto-ssl#71]
Hi,

This is more of a question than an issue. I've noticed that restarting nginx clears my lets encrypt certificates from file storage. Is this expected behaviour or is there a config option I am missing to keep certificates upon restarting nginx? 

Thanks

**Comment by luto** [comment]
That would be a severe bug in my opinion, since it triggers way more certificate issues than necessary. I'll take a look later.

**Comment by luto** [comment]
Sadly I cannot reproduce this with version `0.10.4-1` or `0.10.2-1` and openresty `1.11.2.3-9.el7.centos`.

@jackmiller334 I need you help with that. Which version and environment are you using?

**Comment by luto** [comment]
Oh, I'm missing a couple of versions here. So, for the sake of completeness: restarting also works using `0.10.6-1`.

**Comment by jackmiller334** [comment]
Thanks for taking a look, I am running inside a Docker container built from the base centos:7 image.

 - openresty `1.11.2.2` built from source inside a centos 7 docker image. 
 - Luarocks `2.3.0`, built from source
 - lua-resty-auto-ssl `0.10.6-1`, installed using luarocks

**Comment by luto** [comment]
Would you mind sharing your simplified Dockerfile?

**Comment by jackmiller334** [comment]
Hi, I believe I have solved the issue. I had  ```auto_ssl:set("dir", "/tmp")```, so /tmp would be wiped. I updated my config to use a new directory and gave it the correct permissions. I restarted nginx 10 times and the certificate was served promptly each time without another letsencrypt request being made.

Thank you for looking into my issue 😄

**Comment by luto** [comment]
Glad you found the cause of your issue :)
