### ISSUE TITLE
SSL certificate issue

### ISSUE THREAD

**Issue by soubhagyadiku** [GUI/lua-resty-auto-ssl#74]
Hi,

We have implemented lua-resty-auto-ssl for few stage server and it's working fine, but today while i was implementing it in another stage server one URL has taken the lets encrypt certificate while rest url's are taking self-signed certificate.
I checked the logs and found below:

> 27.0.0.1 [04/Jun/2017:17:00:28 +0300] 127.0.0.1 5 - [-] 0.000 "POST /deploy-challenge HTTP/1.1" 200"-" "curl/7.35.0"
> 127.0.0.1 [04/Jun/2017:17:00:29 +0300] 127.0.0.1 5 - [-] 0.000 "POST /clean-challenge HTTP/1.1" 200"-" "curl/7.35.0"
> 127.0.0.1 [04/Jun/2017:17:00:49 +0300] 127.0.0.1 5 - [-] 0.000 "POST /deploy-challenge HTTP/1.1" 200"-" "curl/7.35.0"
> 127.0.0.1 [04/Jun/2017:17:00:51 +0300] 127.0.0.1 5 - [-] 0.000 "POST /clean-challenge HTTP/1.1" 200"-" "curl/7.35.0"

Can anyone plz help me out to resolve the issue
Thanks in advance for your help.

**Comment by luto** [comment]
I'm sorry that auto-ssl isn't working as you planned. Can you show us what your `allow_domain` function looks like? The log entries you pasted are from the access log; is there anything in the error logs?

**Comment by soubhagyadiku** [comment]
Please see below for allow domain function
init_by_lua_block {
        auto_ssl = (require "resty.auto-ssl").new()
        auto_ssl:set("dir", "/var/openresty/resty-auto-ssl")
                auto_ssl:set("allow_domain", function(domain)
                                        return true
                                    end)
        auto_ssl:init()
    }

**Comment by soubhagyadiku** [comment]
There is nothing in the nginx.error log, the above error i have taken from access.log. Can you please tell me why we are getting this error. Is there any limit that we can maximum get certificate for a specific domain in a month/week.

**Comment by soubhagyadiku** [comment]
Hi,
Yesterday I was checking the error log, and i found this. Is there any limit to get the certificate per week.
Details:
{
"type": "urn:acme:error:rateLimited",
"detail": "Error creating new cert :: too many certificates already issued for:xxxx.info",
"status": 429
}

**Comment by aviatrix** [comment]
This would mean you are not storing them properly and requesting new certificates all the time, AFAIK

**Comment by soubhagyadiku** [comment]
Thanks for the update. But is not generating the certificate. We are getting only the privatekey.pem and cert.csr file. 
-rw-------. 1 root root 3243 Jun  5 08:06 privkey-1496646371.pem
-rw-------. 1 root root 1687 Jun  5 08:06 cert-1496646371.csr
-rw-------. 1 root root    0 Jun  5 08:06 cert-1496646371.pem

We have 4 subdomains configured on this same server, We get certificate for one subdomain while for rest 3 it's using the fallback certificate.

The error we are getting 

Processing xxxx.xxxx.info
 + Signing domains...
 + Generating private key...
 + Generating signing request...
 + Requesting challenge for xxxx.xxxx.info...
 + Responding to challenge for xxxx.xxxx.info 
 + Challenge is valid!
 + Requesting certificate...
 err: # !! WARNING !! Extra configuration directory /var/openresty/resty-auto-ssl/letsencrypt/conf.d exists, but no configuration found in it.
+ HANDLER=deploy_challenge
+ shift
+ deploy_challenge   xxxx.xxxx.info iDBFmn-nNDi-01kj1uXlwVwbforO0EcFSQvA0bSuiFw iDBFmn-nNDi-01kj1uXlwVwbforO0EcFSQvA0bSuiFw.SsEPaduJ6Cb1TSpQ9LbM3uqQ5CfGz_TAUbo7W0TfXPk
+ local DOMAIN=xxx.xxx.info TOKEN_FILENAME=iDBFmn-nNDi-01kj1uXlwVwbforO0EcFSQvA0bSuiFw TOKEN_VALUE=iDBFmn-nNDi-01kj1uXlwVwbforO0EcFSQvA0bSuiFw.SsEPaduJ6Cb1TSpQ9LbM3uqQ5CfGz_TAUbo7W0TfXPk
+ curl --silent --show-error --fail -XPOST --header 'X-Hook-Secret: 40b9c8c4f5268bfada374b819e8d2d1148d0bcd5068fe61e3ac61e81a76f490d' --data-urlencode domain=xxx.xxx.info --data-urlencode token_filename=iDBFmn-nNDi-01kj1uXlwVwbforO0EcFSQvA0bSuiFw --data-urlencode token_value=iDBFmn-nNDi-01kj1uXlwVwbforO0EcFSQvA0bSuiFw.SsEPaduJ6Cb1TSpQ9LbM3uqQ5CfGz_TAUbo7W0TfXPk http://127.0.0.1:8999/deploy-challenge
+ HANDLER=clean_challenge
+ shift
+ clean_challenge xxx.xxx.info iDBFmn-nNDi-01kj1uXlwVwbforO0EcFSQvA0bSuiFw iDBFmn-nNDi-01kj1uXlwVwbforO0EcFSQvA0bSuiFw.SsEPaduJ6Cb1TSpQ9LbM3uqQ5CfGz_TAUbo7W0TfXPk
+ local DOMAIN=xxx.xxx.info TOKEN_FILENAME=iDBFmn-nNDi-01kj1uXlwVwbforO0EcFSQvA0bSuiFw TOKEN_VALUE=iDBFmn-nNDi-01kj1uXlwVwbforO0EcFSQvA0bSuiFw.SsEPaduJ6Cb1TSpQ9LbM3uqQ5CfGz_TAUbo7W0TfXPk
+ curl --silent --show-error --fail -XPOST --header 'X-Hook-Secret: 40b9c8c4f5268bfada374b819e8d2d1148d0bcd5068fe61e3ac61e81a76f490d' --data-urlencode domain=xxx.xxx.info --data-urlencode token_filename=iDBFmn-nNDi-01kj1uXlwVwbforO0EcFSQvA0bSuiFw --data-urlencode token_value=iDBFmn-nNDi-01kj1uXlwVwbforO0EcFSQvA0bSuiFw.SsEPaduJ6Cb1TSpQ9LbM3uqQ5CfGz_TAUbo7W0TfXPk http://127.0.0.1:8999/clean-challenge
  + ERROR: An error occurred while sending post-request to https://acme-v01.api.letsencrypt.org/acme/new-cert (Status 429)

Details:
{
  "type": "urn:acme:error:rateLimited",
  "detail": "Error creating new cert :: too many certificates already issued for: xxx.info",
  "status": 429
}

**Comment by soubhagyadiku** [comment]
Any update on this plz

**Comment by luto** [comment]
This means that your server is caught in one of [let's encrypts rate limits](https://letsencrypt.org/docs/rate-limits/). Probably the 25 certificates per domain per week one. Is your `/var/openresty/resty-auto-ssl` directory permanent when your server reboots? Are you hosting openresty inside docker (if yes: did you mount that directory to somewhere permanent outside the container)?

**Comment by soubhagyadiku** [comment]
Thanks Luto for the update.
Yes, We are using both Docker and Non-Docker setup and in docker we have done volume mapping from host to container.
In fact few days before i have configured for few more stage server and all working fine, so i we have reached the rate limit. I was not aware of that Lets Encrypt Rate limit.

**Comment by luto** [comment]
That's good to hear! I guess your issue is solved now, so I'm going to close this issue. If that's not the case, just reopen it, please. If you encounter any further problems, please open a new one. Thanks!

**Comment by soubhagyadiku** [comment]
Hi Luto,

Hope you are doing well!

Last week, i have generated only 4-5 certificates using resty-auto-ssl for few domains, but again i am getting the same error i.e. Rate limit in the error log. Is there any way to check how many certificates we have generated per week basis. As far as i know, we can generate 20 certificates per week, please correct me if i am wrong.

Can you please tell me what could be the problem.

The error we are getting

Processing xxxx.xxxx.info

Signing domains...
Generating private key...
Generating signing request...
Requesting challenge for xxxx.xxxx.info...
Responding to challenge for xxxx.xxxx.info
Challenge is valid!
Requesting certificate...
err: # !! WARNING !! Extra configuration directory /var/openresty/resty-auto-ssl/letsencrypt/conf.d exists, but no configuration found in it.
HANDLER=deploy_challenge
shift
deploy_challenge xxxx.xxxx.info iDBFmn-nNDi-01kj1uXlwVwbforO0EcFSQvA0bSuiFw iDBFmn-nNDi-01kj1uXlwVwbforO0EcFSQvA0bSuiFw.SsEPaduJ6Cb1TSpQ9LbM3uqQ5CfGz_TAUbo7W0TfXPk
local DOMAIN=xxx.xxx.info TOKEN_FILENAME=iDBFmn-nNDi-01kj1uXlwVwbforO0EcFSQvA0bSuiFw TOKEN_VALUE=iDBFmn-nNDi-01kj1uXlwVwbforO0EcFSQvA0bSuiFw.SsEPaduJ6Cb1TSpQ9LbM3uqQ5CfGz_TAUbo7W0TfXPk
curl --silent --show-error --fail -XPOST --header 'X-Hook-Secret: 40b9c8c4f5268bfada374b819e8d2d1148d0bcd5068fe61e3ac61e81a76f490d' --data-urlencode domain=xxx.xxx.info --data-urlencode token_filename=iDBFmn-nNDi-01kj1uXlwVwbforO0EcFSQvA0bSuiFw --data-urlencode token_value=iDBFmn-nNDi-01kj1uXlwVwbforO0EcFSQvA0bSuiFw.SsEPaduJ6Cb1TSpQ9LbM3uqQ5CfGz_TAUbo7W0TfXPk http://127.0.0.1:8999/deploy-challenge
HANDLER=clean_challenge
shift
clean_challenge xxx.xxx.info iDBFmn-nNDi-01kj1uXlwVwbforO0EcFSQvA0bSuiFw iDBFmn-nNDi-01kj1uXlwVwbforO0EcFSQvA0bSuiFw.SsEPaduJ6Cb1TSpQ9LbM3uqQ5CfGz_TAUbo7W0TfXPk
local DOMAIN=xxx.xxx.info TOKEN_FILENAME=iDBFmn-nNDi-01kj1uXlwVwbforO0EcFSQvA0bSuiFw TOKEN_VALUE=iDBFmn-nNDi-01kj1uXlwVwbforO0EcFSQvA0bSuiFw.SsEPaduJ6Cb1TSpQ9LbM3uqQ5CfGz_TAUbo7W0TfXPk
curl --silent --show-error --fail -XPOST --header 'X-Hook-Secret: 40b9c8c4f5268bfada374b819e8d2d1148d0bcd5068fe61e3ac61e81a76f490d' --data-urlencode domain=xxx.xxx.info --data-urlencode token_filename=iDBFmn-nNDi-01kj1uXlwVwbforO0EcFSQvA0bSuiFw --data-urlencode token_value=iDBFmn-nNDi-01kj1uXlwVwbforO0EcFSQvA0bSuiFw.SsEPaduJ6Cb1TSpQ9LbM3uqQ5CfGz_TAUbo7W0TfXPk http://127.0.0.1:8999/clean-challenge
ERROR: An error occurred while sending post-request to https://acme-v01.api.letsencrypt.org/acme/new-cert (Status 429)
Details:
{
"type": "urn:acme:error:rateLimited",
"detail": "Error creating new cert :: too many certificates already issued for: xxx.info",
"status": 429
}

**Comment by cpu** [comment]
>  there any way to check how many certificates we have generated per week basis.

You might find [lectl](https://github.com/sahsanu/lectl) helpful. You can also search the [certificate transparency logs](https://crt.sh) for your domain directly. All Let's Encrypt issued certificates for your domains will be logged to the certificate transparency ecosystem.

**Comment by soubhagyadiku** [comment]
Thanks @cpu
