### ISSUE TITLE
Permission denied to connect to unix:/tmp/shell.sock?

### ISSUE THREAD

**Issue by domahub** [GUI/lua-resty-auto-ssl#80]
```
2017/07/12 01:18:53 [crit] 8745#8745: *354 connect() to unix:/tmp/shell.sock failed (13: Permission denied), context: ssl_certificate_by_lua*, client: XXX.XXX.XXX.XXX, server: 0.0.0.0:443

2017/07/12 01:18:53 [error] 8745#8745: *354 [lua] lets_encrypt.lua:40: issue_cert(): auto-ssl: dehydrated failed: env HOOK_SECRET=abb47edea45f9f2177f69ab906ece2f4ab949aa11317edbbd66c5d451189c083 HOOK_SERVER_PORT=8999 /usr/local/bin/resty-auto-ssl/dehydrated --cron --no-lock --domain eraisawesome.com --challenge http-01 --config /etc/resty-auto-ssl/letsencrypt/config --hook /usr/local/bin/resty-auto-ssl/letsencrypt_hooks status: -2 out: nil err: permission denied, context: ssl_certificate_by_lua*, client: XXX.XXX.XXX.XXX, server: 0.0.0.0:443`

2017/07/12 01:18:53 [error] 8745#8745: *354 [lua] ssl_certificate.lua:92: issue_cert(): auto-ssl: issuing new certificate failed: dehydrated failure, context: ssl_certificate_by_lua*, client: XXX.XXX.XXX.XXX, server: 0.0.0.0:443`

2017/07/12 01:18:53 [error] 8745#8745: *354 [lua] ssl_certificate.lua:256: auto-ssl: could not get certificate for eraisawesome.com - using fallback - failed to get or issue certificate, context: ssl_certificate_by_lua*, client: XXX.XXX.XXX.XXX, server: 0.0.0.0:443
```

Hello! I installed lua-resty-auto-ssl on my test server, but was unable to get it working. I am getting the above error, anybody have an idea as to why? Thank you very much!

**Comment by luto** [comment]
Hey there. I took the liberty of reformatting your issue a bit, so it's more easily readable. It's not totally clear to me yet, why auto-ssl is failing in your setup. Can you please answer the following questions?
* What are the permissions (`ls -l` command) of `/tmp/shell.sock` while nginx is running?
* Which user is your nginx master running as? Which one for the the workers?
* Is SELinux enabled; if yes, are there any entries in `/var/log/audit/audit.log` about `shell.sock`?

**Comment by domahub** [comment]
Hey Luto, 

Thanks for formatting my question for me, I wasn't sure how to do that.

I changed the nginx.conf from

`user www-data`

to

`user root` 

Just for testing purposes and everything worked perfectly! Obviously this won't fly for production, but this definitely lets me know it's something to do with permissions...

As far as your questions go--

- I initially thought it might be a permissions thing on `/tmp/shell.sock` so I tried doing a chmod 775 on it--right now it's `srwxr-xr-x 1 nobody no group`
- I am not sure what you mean by nginx master vs workers, this is only 1 server. (I'm new to nginx, sorry!)
- I don't have a `/audit/` directory under `/var/log/`

**Comment by domahub** [comment]
I ran a `chown www-data /tmp/shell.sock` and the problem seems to have disappeared. Not sure what the security implications are for changing the permissions on that file...but at least the error message disappeared and certificates are creating by the `www-data` user! 

Thanks @luto

**Comment by GUI** [comment]
I think what perhaps happened was that nginx was started without a `user` setting initially. This defaults to running the worker processes as `nobody`, and would have resulted in the `/tmp/shell.sock` to be owned by `nobody`. If, at a later point, nginx was adjusted to add the `user www-data` configuration, then after the next restart this would have led to this permission problem (since the the `/tmp/shell.sock` file already existed and was owned by `nobody`, but the `www-data` user couldn't read it).

Similar situations could crop up if you ever change the nginx `user` configuration to a different user.

So I'm going to go ahead and close this, but hopefully this issue will be useful if anyone runs into similar issues in the future.
