### ISSUE TITLE
Is there a way to redirect the request to a different URL based on some condition?

### ISSUE THREAD

**Issue by domahub** [GUI/lua-resty-auto-ssl#82]
Hello!

I currently have the `auto_ssl:set("allow_domain")` function working with a custom API I wrote to allow for specific domains. However, when there is a domain that I **don't** want SSL certificates for, I would like to redirect that request to an entirely different URL. Is there a way to accomplish that?

Thank you very much!

**Comment by domahub** [comment]
Basically instead of relying on a fallback cert, can I redirect the request to a different URL?

**Comment by luto** [comment]
> when there is a domain that I don't want SSL certificates for, I would like to redirect that request to an entirely different URL.

if that clients connects via HTTPS the very first thing that needs to be handled is the TLS session. Redirects, error messages and all the other HTTP stuff can only happen _after_ the TLS session is established. This means that you can of course redirect any client to any site, but only after either giving them a valid certificate or the fallback one.

Redirecting a HTTPS client without browser-errors/warnings and without a valid certificate is not possible.

**Comment by luto** [comment]
To keep the issue list clean, I'll close this one. In case I misunderstood your question of if you've got any further questions, just reply, please! :)
