### ISSUE TITLE
Luarocks deprecated? 

### ISSUE THREAD

**Issue by domahub** [GUI/lua-resty-auto-ssl#83]
Hello,

The Readme states that we must install [Luarocks](http://openresty.org/en/using-luarocks.html), but on that page, it states that using Luarocks with Openresty is deprecated since OpenResty provides its own package manager, OPM.

Does this mean we shouldn't be installing Luarocks?

Thank you!

**Comment by domahub** [comment]
Trying to use OPM to find lua-resty-auto-ssl says it's not available, I'm assuming that this package hasn't been uploaded to OPM so we should still utilize Luarocks to install?

**Comment by luto** [comment]
Yes, luarocks is being depricated, but OPM is not yet able to actually install auto-ssl, since it does not support binary packages. See https://github.com/GUI/lua-resty-auto-ssl/issues/45 for more details.
