### ISSUE TITLE
How to check if we have a certificate for a domain? 

### ISSUE THREAD

**Issue by dimitrovs** [GUI/lua-resty-auto-ssl#86]
Given the publicly exposed methods,  what's the easiest way to check if my lua-resty-auto-ssl instance currently has a certificate for domain x.y.z? I am using file-based storage. I want to use this in another place in my configuration.

**Comment by luto** [comment]
Do you want to check a domain name inside the current nginx process or externally via some script (e.g. for monitoring)?

Internal access: Certificates are stored in two stages: memory cache and actual file/redis/whatever store. Within auto-ssl there is a function [`ssl_certificate.lua:get_cert`](https://github.com/GUI/lua-resty-auto-ssl/blob/master/lib/resty/auto-ssl/ssl_certificate.lua#L99), which first checks the cache, then store and then (sadly) requests a new certificate. So this is not what you want. You are probably best off [using the storage driver directly](https://github.com/GUI/lua-resty-auto-ssl/blob/master/lib/resty/auto-ssl/ssl_certificate.lua#L107-L113).

External access: Your best bet would probably to check for a file in `/etc/resty-auto-ssl/storage/file`. Another way would be firing up a [openresty-cli](https://github.com/openresty/resty-cli) session to use the "internal access" way. Although, I've got no idea if that actually works ;)

Please note that none of these methods are publicly documented. At the moment there is no public API, so the details are sadly subject to change without notice. It would be very nice to have a defined set of APIs, though. If you've got some spare time, I'd love to see a PR.

**Comment by dimitrovs** [comment]
Thanks. It's internal for the process.  I want to detect the case where users are sending bogus host header not registered in the DNS, in this case the SSL issuance will fail but they may proceed with the self-signed cert, something I am trying to prevent. I will keep the need for API documentation in mind because your project is extremely useful for me and I would love to give back when I get a chance.

**Comment by dimitrovs** [comment]
Hi,
I have been using this code to check if we have a certificate for a given domain:

```
local domain_cert = ngx.shared.auto_ssl:get("domain:fullchain_der:" .. requested_domain)
local domain_key = ngx.shared.auto_ssl:get("domain:privkey_der:" .. requested_domain)
if not domain_cert or not domain_key then
    ngx.exit(403)
end
```
It mostly works. But after some time it appears the cert (or key) is no longer found (so my if statement triggers) even though Nginx continues to serve a correct certificate. After a few minutes and a refresh both the key and certificate appear in the dictionary again. Do you have an idea what may be causing this intermittent issue?

**Comment by dimitrovs** [comment]
I am pretty sure the problem happens during certificate renewal or as a result of entry expiry in the dictionary. I don't have many domains and the server was definitely not restarted. I decided to keep a parallel dictionary with the set of domains which I update every time ngx.shared.auto_ssl returns a certificate for the given domain. I will test it for a few days, hopefully the issue doesn't come back.

Using the storage driver is not that trivial, I don't have access to the auto_ssl_instance.
