### ISSUE TITLE
Certificate renew didn't happened for few domains

### ISSUE THREAD

**Issue by soubhagyadiku** [GUI/lua-resty-auto-ssl#90]
Hi All,

We have implemented resty-auto-ssl in our stage server and all domains are working as HTTPS, but for few domains the certificate renew didn't happen while as for others the ssl certificate got renewed. All the certificates were issued for all domains on the same day for the first time. Now 2 domains are not getting renewed.
We are running Nginx as docker and we have done the volume map for certificate directory from host.
The error we are getting is as follows:
2017/08/29 14:38:37 [error] 21#0: *7928 [lua] lets_encrypt.lua:24: issue_cert(): auto-ssl: dehydrated failed: env HOOK_SECRET=2477eb0274dc5f3d0bfda65d05799c0a663e844c6b925f0b32f3cf30ed2ab7cd /usr/local/openresty/luajit/share/lua/5.1/resty/auto-ssl/vendor/dehydrated --cron --no-lock --domain xxx.xxx.xxx.info --challenge http-01 --config /var/openresty/resty-auto-ssl/letsencrypt/config --hook /usr/local/openresty/luajit/share/lua/5.1/resty/auto-ssl/shell/letsencrypt_hooks status: 256 out: # INFO: Using main config file /var/openresty/resty-auto-ssl/letsencrypt/config
Processing xxx.xxx.xxx.info
 + Checking domain name(s) of existing cert... unchanged.
 + Checking expire date of existing cert...
 + Valid till Aug 31 04:37:00 2017 GMT (Less than 30 days). Renewing!
 + Signing domains...
 + Generating private key...
 + Generating signing request...
 + Requesting challenge for xxx.xxx.xxx.info...
 + Responding to challenge for xxx.xxx.xxx.info...
 + Challenge is valid!
 + Requesting certificate...
 err: # !! WARNING !! Extra configuration directory /var/openresty/resty-auto-ssl/letsencrypt/conf.d exists, but no configuration found in it.
+ HANDLER=deploy_challenge
+ shift
+ deploy_challenge xxx.xxx.xxx.info cUU0FjSAtUpO1e_sZ0XHFXAguDZvwR6v2YDEIQtIVcQ cUU0FjSAtUpO1e_sZ0XHFXAguDZvwR6v2YDEIQtIVcQ.S1OG0_7e_DlFEP2x_WUbDhq3ZPM1avyHIiE5XcVZ7ug
+ local DOMAIN=xxx.xxx.xxx.info TOKEN_FILENAME=cUU0FjSAtUpO1e_sZ0XHFXAguDZvwR6v2YDEIQtIVcQ TOKEN_VALUE=cUU0FjSAtUpO1e_sZ0XHFXAguDZvwR6v2YDEIQtIVcQ.S1OG0_7e_DlFEP2x_WUbDhq3ZPM1avyHIiE5XcVZ7ug
+ curl --silent --show-error --fail -XPOST --header 'X-Hook-Secret: 2477eb0274dc5f3d0bfda65d05799c0a663e844c6b925f0b32f3cf30ed2ab7cd' --data-urlencode domain=xxx.xxx.xxx.info --data-urlencode token_filename=cUU0FjSAtUpO1e_sZ0XHFXAguDZvwR6v2YDEIQtIVcQ --data-urlencode token_value=cUU0FjSAtUpO1e_sZ0XHFXAguDZvwR6v2YDEIQtIVcQ.S1OG0_7e_DlFEP2x_WUbDhq3ZPM1avyHIiE5XcVZ7ug http://127.0.0.1:8999/deploy-challenge
+ HANDLER=clean_challenge
+ shift
+ clean_challenge xxx.xxx.xxx.info cUU0FjSAtUpO1e_sZ0XHFXAguDZvwR6v2YDEIQtIVcQ cUU0FjSAtUpO1e_sZ0XHFXAguDZvwR6v2YDEIQtIVcQ.S1OG0_7e_DlFEP2x_WUbDhq3ZPM1avyHIiE5XcVZ7ug
+ local DOMAIN=xxx.xxx.xxx.info TOKEN_FILENAME=cUU0FjSAtUpO1e_sZ0XHFXAguDZvwR6v2YDEIQtIVcQ TOKEN_VALUE=cUU0FjSAtUpO1e_sZ0XHFXAguDZvwR6v2YDEIQtIVcQ.S1OG0_7e_DlFEP2x_WUbDhq3ZPM1avyHIiE5XcVZ7ug
+ curl --silent --show-error --fail -XPOST --header 'X-Hook-Secret: 2477eb0274dc5f3d0bfda65d05799c0a663e844c6b925f0b32f3cf30ed2ab7cd' --data-urlencode domain=xxx.xxx.xxx.info --data-urlencode token_filename=cUU0FjSAtUpO1e_sZ0XHFXAguDZvwR6v2YDEIQtIVcQ --data-urlencode token_value=cUU0FjSAtUpO1e_sZ0XHFXAguDZvwR6v2YDEIQtIVcQ.S1OG0_7e_DlFEP2x_WUbDhq3ZPM1avyHIiE5XcVZ7ug http://127.0.0.1:8999/clean-challenge
  + ERROR: An error occurred while sending post-request to https://acme-v01.api.letsencrypt.org/acme/new-cert (Status 429)

Details:
{
  "type": "urn:acme:error:rateLimited",
  "detail": "Error creating new cert :: too many certificates already issued for exact set of domains: xxx.xxx.xxx.info",
  "status": 429
}

+ HANDLER=clean_challenge
+ shift
+ clean_challenge cUU0FjSAtUpO1e_sZ0XHFXAguDZvwR6v2YDEIQtIVcQ cUU0FjSAtUpO1e_sZ0XHFXAguDZvwR6v2YDEIQtIVcQ.S1OG0_7e_DlFEP2x_WUbDhq3ZPM1avyHIiE5XcVZ7ug
/usr/local/openresty/luajit/share/lua/5.1/resty/auto-ssl/shell/letsencrypt_hooks: line 24: 3: unbound variable
, context: ngx.timer

Can you please help me out to resolve the issue.
Thanks,
Soubhagya

**Comment by Snowmanko** [comment]
"type": "urn:acme:error:rateLimited",
"detail": "Error creating new cert :: too many certificates already issued for exact set of domains: xxx.xxx.xxx.info"

You are probably hit rate limit of Let's Encrypt. See https://letsencrypt.org/docs/rate-limits/

**Comment by soubhagyadiku** [comment]
Hi Snowmanko,

AFAIK there is no limitation in certificate renewal.

Actually the URL was running as https and we have the letsencypt certificate which was expired on 31st Aug 2017. But it didn't get renewed before 31st Aug, don't know why? But today when i checked, the certificate was got renewed.

Thank you for ur comments.

**Comment by Snowmanko** [comment]
Are you sure ?

> Renewals are still subject to the Duplicate Certificate limit.

**Comment by soubhagyadiku** [comment]
I have not checked about the Duplicate Certificate limit for renewal.

**Comment by luto** [comment]
Since this seems to be related to be rate limits imposed by let's encrypt and not auto-ssl itself, I am closing this for now. Please feel free to reopen this issue, if there are new problems of this kind.
