### ISSUE TITLE
Use Let'sEncrypt Certs without triggering getting new ones.

### ISSUE THREAD

**Issue by mklauber** [GUI/lua-resty-auto-ssl#91]
Hello, our situation is that we've got 30k+ domains, and we're trying to get things setup for SSL.  The problem we're running into is that we're getting so many requests for new domains, that by the time Let's Encrypt checks the challenge url, we've gotten a new request which has replaced the token.  

What we'd like to do is setup the `ssl_certificate_by_lua_block` to use the Let's Encrypt certificate for the domain only if it already exists.  Then on a separate port, we'd setup the server that can trigger the Let's Encrypt request.  That way we can make the certificate requests one at a time, sequentially.

**Comment by mklauber** [comment]
Looking at the code, it seems like encapsulating https://github.com/GUI/lua-resty-auto-ssl/blob/master/lib/resty/auto-ssl/ssl_certificate.lua#L116 in an if statement would do what I want, but `get_cert` doesn't get passed `ssl_options` from `do_ssl`.

**Comment by GUI** [comment]
Closed by #92 and part of v0.12.0. Thanks!
