### ISSUE TITLE
why not use shcache to control the logic

### ISSUE THREAD

**Issue by hy05190134** [GUI/lua-resty-auto-ssl#95]
https://github.com/GUI/lua-resty-auto-ssl/blob/a776da502b0aef55a603e060897351966426b570/lib/resty/auto-ssl/ssl_certificate.lua#L58

**Comment by Cl1608Ho** [comment]
Could we close this?

**Comment by hy05190134** [comment]
@Cl1608Ho  why close it?

**Comment by Cl1608Ho** [comment]
Duplicate issue #96; without content

**Comment by hy05190134** [comment]
@Cl1608Ho  since you have relate it with #96, you can close it
